import type { ContentSourceMeta, LocalizedString } from "./types";

export type LegacyMembershipPlan = {
  audience: LocalizedString;
  tier: string;
  price: number;
  capacity: number;
  benefits: LocalizedString[];
  meta: ContentSourceMeta;
};

const meta: ContentSourceMeta = {
  sourceUrls: ["https://qbbe.ca/membership-plans/"], migratedAt: "2026-08-17", migratedBy: "Website 2.0 migration",
  verificationStatus: "needs-editorial-review", notes: "2021 QBBE Donor Program Structure. Historic source only; do not enable payment or describe as a current benefit package without QBBE leadership and finance approval.", translation: { en: "needs-review", fr: "needs-review" },
};
const benefit = (en: string, fr: string) => ({ en, fr });

export const legacyMembershipPlans: LegacyMembershipPlan[] = [
  { audience: benefit("Corporate Allies", "Alliés corporatifs"), tier: "Gold", price: 5000, capacity: 5, benefits: [benefit("Legacy source includes board-meeting access, consultative-body participation, advocacy and communications access, networking, event discounts, and two Lunch & Learn sessions.", "La source historique comprend l’accès aux réunions du conseil, la participation au corps consultatif, l’accès au plaidoyer et aux communications, le réseautage, des rabais sur les événements et deux séances Lunch & Learn.")], meta },
  { audience: benefit("Corporate Allies", "Alliés corporatifs"), tier: "Silver", price: 2500, capacity: 5, benefits: [benefit("Legacy source includes board minutes, consultative participation, networking, advocacy, research access, event discounts, and one Lunch & Learn session.", "La source historique comprend les procès-verbaux du conseil, la participation consultative, le réseautage, le plaidoyer, l’accès à la recherche, des rabais sur les événements et une séance Lunch & Learn.")], meta },
  { audience: benefit("Corporate Allies", "Alliés corporatifs"), tier: "Bronze", price: 1000, capacity: 5, benefits: [benefit("Legacy source includes consultative participation, networking, advocacy, communications, event discounts, and a discounted Lunch & Learn session.", "La source historique comprend la participation consultative, le réseautage, le plaidoyer, les communications, des rabais sur les événements et une séance Lunch & Learn à prix réduit.")], meta },
  { audience: benefit("Local Business Allies", "Alliés entreprises locales"), tier: "Gold", price: 750, capacity: 5, benefits: [benefit("Legacy source includes board-meeting access, consultative participation, networking, advocacy, research access, event discounts, and one Lunch & Learn session.", "La source historique comprend l’accès aux réunions du conseil, la participation consultative, le réseautage, le plaidoyer, l’accès à la recherche, des rabais sur les événements et une séance Lunch & Learn.")], meta },
  { audience: benefit("Local Business Allies", "Alliés entreprises locales"), tier: "Silver", price: 500, capacity: 5, benefits: [benefit("Legacy source includes consultative participation, board minutes, networking, advocacy, research access, and event discounts.", "La source historique comprend la participation consultative, les procès-verbaux du conseil, le réseautage, le plaidoyer, l’accès à la recherche et des rabais sur les événements.")], meta },
  { audience: benefit("Local Business Allies", "Alliés entreprises locales"), tier: "Bronze", price: 250, capacity: 5, benefits: [benefit("Legacy source includes board minutes, member-network access, advocacy, communications, research-database access, and event discounts.", "La source historique comprend les procès-verbaux du conseil, l’accès au réseau des membres, le plaidoyer, les communications, l’accès à une base de recherche et des rabais sur les événements.")], meta },
  { audience: benefit("Allies in Education", "Alliés en éducation"), tier: "Gold", price: 150, capacity: 50, benefits: [benefit("Legacy source includes board minutes, education-partner networking, mentorship, advocacy, research access, event discounts, and a QBBE T-shirt.", "La source historique comprend les procès-verbaux du conseil, le réseautage avec des partenaires éducatifs, le mentorat, le plaidoyer, l’accès à la recherche, des rabais sur les événements et un t-shirt QBBE.")], meta },
  { audience: benefit("Allies in Education", "Alliés en éducation"), tier: "Silver", price: 100, capacity: 75, benefits: [benefit("Legacy source includes public board minutes, education-partner employment opportunities, mentorship, advocacy, research access, and event discounts.", "La source historique comprend les procès-verbaux publics du conseil, des occasions d’emploi avec des partenaires éducatifs, le mentorat, le plaidoyer, l’accès à la recherche et des rabais sur les événements.")], meta },
  { audience: benefit("Allies in Education", "Alliés en éducation"), tier: "Bronze", price: 50, capacity: 100, benefits: [benefit("Legacy source includes public board minutes, education-partner opportunities, advocacy, communications, research-database access, and event discounts.", "La source historique comprend les procès-verbaux publics du conseil, des occasions avec des partenaires éducatifs, le plaidoyer, les communications, l’accès à une base de recherche et des rabais sur les événements.")], meta },
  { audience: benefit("Community & Individual Allies", "Alliés communautaires et individuels"), tier: "Gold", price: 150, capacity: 20, benefits: [benefit("Legacy source includes board-meeting access, consultative participation, minutes, networking, mentorship, volunteer and advocacy opportunities, research access, event discounts, and a QBBE T-shirt.", "La source historique comprend l’accès aux réunions du conseil, la participation consultative, les procès-verbaux, le réseautage, le mentorat, des occasions de bénévolat et de plaidoyer, l’accès à la recherche, des rabais sur les événements et un t-shirt QBBE.")], meta },
  { audience: benefit("Community & Individual Allies", "Alliés communautaires et individuels"), tier: "Silver", price: 100, capacity: 25, benefits: [benefit("Legacy source includes consultative participation, board minutes, networking, mentorship, advocacy, research access, and event discounts.", "La source historique comprend la participation consultative, les procès-verbaux du conseil, le réseautage, le mentorat, le plaidoyer, l’accès à la recherche et des rabais sur les événements.")], meta },
  { audience: benefit("Community & Individual Allies", "Alliés communautaires et individuels"), tier: "Bronze", price: 50, capacity: 30, benefits: [benefit("Legacy source includes board minutes, member-network access, volunteer opportunities, advocacy, research-database access, and event discounts.", "La source historique comprend les procès-verbaux du conseil, l’accès au réseau des membres, des occasions de bénévolat, le plaidoyer, l’accès à une base de recherche et des rabais sur les événements.")], meta },
  { audience: benefit("Community & Individual Allies", "Alliés communautaires et individuels"), tier: "Basic", price: 25, capacity: 50, benefits: [benefit("Legacy source includes board minutes, member-network access, advocacy, and research-database access.", "La source historique comprend les procès-verbaux du conseil, l’accès au réseau des membres, le plaidoyer et l’accès à une base de recherche.")], meta },
];
