import type { ContentSourceMeta, FAQItem, Report } from "./types";

const migratedAt = "2026-08-17";
const source = (sourceUrls: string[], verificationStatus: ContentSourceMeta["verificationStatus"], notes?: string): ContentSourceMeta => ({ sourceUrls, migratedAt, migratedBy: "Website 2.0 migration", verificationStatus, notes, translation: { en: "needs-review", fr: "needs-review" } });

export const organization = {
  legalName: "Quebec Board of Black Educators",
  publicName: "QBBE",
  phone: "(514) 481-9400",
  primaryEmail: "info@qbbe.ca",
  address: "5050 Côte Saint Luc Rd, Montreal, Quebec H3W 2H1",
  officeHours: { en: "Monday–Friday, 9 am–4 pm", fr: "Du lundi au vendredi, de 9 h à 16 h" },
  meta: source(["https://qbbe.ca/contact-2/", "https://student.qbbe.ca/"], "needs-editorial-review", "Contact information is centralized here. Confirm public hours and bilingual postal style before launch."),
};

export const reports: Report[] = [
  { title: { en: "2020 Annual Report", fr: "Rapport annuel 2020" }, year: 2020, type: "annual-report", language: "en", description: { en: "23-page QBBE annual report, retained as a historical public record.", fr: "Rapport annuel QBBE de 23 pages, conservé comme dossier public historique." }, sourceUrl: "https://qbbe.ca/reports/2020-annual-report/", fileUrl: "https://qbbe.ca/wp-content/uploads/QBBE-Annual-Report-2020-digital-copy.pdf", publishedAt: "2021-12-13", archived: true, meta: source(["https://qbbe.ca/reports/2020-annual-report/", "https://qbbe.ca/wp-content/uploads/QBBE-Annual-Report-2020-digital-copy.pdf"], "needs-editorial-review", "Verified as a publicly reachable 23-page PDF during the 2026-08-17 attachment audit. Confirm continued publication and archival label with QBBE.") },
  { title: { en: "2000 Financial Statement", fr: "États financiers 2000" }, year: 2000, type: "financial-statement", language: "en", description: { en: "Ten-page scanned financial-statement record preserved from QBBE’s public legacy files.", fr: "Dossier numérisé de dix pages d’états financiers, préservé des fichiers publics historiques de QBBE." }, sourceUrl: "https://qbbe.ca/reports/2000-financial-statement/", fileUrl: "https://qbbe.ca/wp-content/uploads/2020/11/Financial-Statements-2000.pdf", publishedAt: "2020-11-06", archived: true, meta: source(["https://qbbe.ca/reports/2000-financial-statement/", "https://qbbe.ca/wp-content/uploads/2020/11/Financial-Statements-2000.pdf"], "needs-editorial-review", "Verified as a publicly reachable 10-page scanned PDF during the 2026-08-17 attachment audit. Confirm continued publication and archival label with QBBE.") },
  { title: { en: "2021 Annual General Meeting Minutes", fr: "Procès-verbal de l’assemblée générale annuelle 2021" }, year: 2021, type: "governance", language: "bilingual", description: { en: "Two-page historical governance record of QBBE’s December 9, 2021 annual general meeting.", fr: "Dossier historique de gouvernance de deux pages sur l’assemblée générale annuelle de QBBE du 9 décembre 2021." }, sourceUrl: "https://qbbe.ca/wp-content/uploads/Minutes-of-AGM-2021.pdf", fileUrl: "https://qbbe.ca/wp-content/uploads/Minutes-of-AGM-2021.pdf", publishedAt: "2022-12-07", archived: true, meta: source(["https://qbbe.ca/wp-content/uploads/Minutes-of-AGM-2021.pdf"], "needs-editorial-review", "Verified public two-page PDF during the 2026-08-17 attachment audit. Contains a former QBBE address and historic attendees; do not treat either as current.") },
];

export const faqs: FAQItem[] = [
  { category: "about", question: { en: "What is QBBE?", fr: "Qu’est-ce que QBBE?" }, answer: { en: "QBBE is a nonprofit education and research institution. Its legacy materials describe work to raise awareness of educational bias and provide academic support and opportunities to communities of colour.", fr: "QBBE est une institution d’éducation et de recherche à but non lucratif. Ses documents historiques décrivent un travail de sensibilisation aux préjugés en éducation et de soutien scolaire et d’occasions pour les communautés de couleur." }, meta: source(["https://qbbe.ca/"], "needs-editorial-review") },
  { category: "about", question: { en: "What is QBBE’s mission?", fr: "Quelle est la mission de QBBE?" }, answer: { en: "To encourage and support continuous improvements in Quebec’s education system and the equitable distribution of its benefits to communities of colour, so programs provide the best opportunity to pursue educational attainment and its social and economic outcomes.", fr: "Encourager et soutenir l’amélioration continue du système d’éducation du Québec et une distribution équitable de ses bénéfices aux communautés de couleur, afin que les programmes offrent les meilleures possibilités de réussite éducative et les retombées sociales et économiques qui en découlent." }, meta: source(["https://qbbe.ca/board-of-directors/"], "needs-editorial-review", "Formal mission retained in meaning from the legacy FAQ; French requires institutional approval.") },
  { category: "about", question: { en: "Is QBBE a government or religious organization?", fr: "QBBE est-il un organisme gouvernemental ou religieux?" }, answer: { en: "The legacy FAQ identifies QBBE as a non-sectarian, non-governmental organization. QBBE should confirm this wording before launch.", fr: "La FAQ historique présente QBBE comme un organisme non confessionnel et non gouvernemental. QBBE doit confirmer cette formulation avant le lancement." }, meta: source(["https://qbbe.ca/board-of-directors/"], "needs-legal-review") },
  { category: "programs", question: { en: "How do I register?", fr: "Comment puis-je m’inscrire?" }, answer: { en: "Use the program page to see whether registration is available. Da Costa Hall and Academic Support currently point to the QBBE student portal; all other program cycles should be confirmed with QBBE.", fr: "Utilisez la page du programme pour voir si les inscriptions sont disponibles. Da Costa Hall et le soutien scolaire renvoient actuellement au portail étudiant QBBE; les autres cycles doivent être confirmés auprès de QBBE." }, meta: source(["https://student.qbbe.ca/"], "needs-program-review") },
  { category: "donations", question: { en: "Are tax receipts issued?", fr: "Des reçus fiscaux sont-ils remis?" }, answer: { en: "Tax-receipt eligibility and wording are under QBBE legal and finance review. Please contact QBBE before relying on a donation for tax purposes.", fr: "L’admissibilité aux reçus fiscaux et la formulation applicable sont en révision juridique et financière chez QBBE. Communiquez avec QBBE avant de vous fier à un don à des fins fiscales." }, meta: source(["https://qbbe.ca/donate/"], "needs-legal-review", "The reviewed public Donate page does not establish tax-receipt eligibility; this FAQ preserves that legal uncertainty rather than inferring a policy.") },
];
