import type { ContentSourceMeta, PageContent } from "./types";

const migratedAt = "2026-08-17";
const qbbe = "https://qbbe.ca/";
const meta = (sourceUrls: string[], verificationStatus: ContentSourceMeta["verificationStatus"], notes?: string): ContentSourceMeta => ({ sourceUrls, migratedAt, migratedBy: "Website 2.0 migration", verificationStatus, notes, translation: { en: "needs-review", fr: "needs-review" } });
const page = (eyebrow: PageContent["eyebrow"], title: PageContent["title"], lead: PageContent["lead"], sections: PageContent["sections"], sourceUrls: string[], verificationStatus: ContentSourceMeta["verificationStatus"], notes?: string): PageContent => ({ eyebrow, title, lead, sections, meta: meta(sourceUrls, verificationStatus, notes) });

export const pages: Record<string, PageContent> = {
  about: page(
    { en: "About QBBE", fr: "À propos de QBBE" }, { en: "An education and research institution rooted in community.", fr: "Une institution d’éducation et de recherche ancrée dans la communauté." },
    { en: "QBBE brings educational support, advocacy, research, and community connection together in Quebec.", fr: "QBBE réunit soutien éducatif, plaidoyer, recherche et liens communautaires au Québec." },
    [{ heading: { en: "What QBBE does", fr: "Ce que fait QBBE" }, paragraphs: [{ en: "QBBE’s public materials describe a nonprofit education and research institution that raises awareness of educational bias and provides academic support and opportunities to communities of colour.", fr: "Les documents publics de QBBE décrivent une institution d’éducation et de recherche à but non lucratif qui sensibilise aux préjugés en éducation et offre du soutien scolaire et des occasions aux communautés de couleur." }] }, { heading: { en: "A wider institutional role", fr: "Un rôle institutionnel élargi" }, paragraphs: [{ en: "Programs for students and families sit alongside research-informed advocacy, community partnerships, and a long history of Black educators acting on educational inequality.", fr: "Les programmes destinés aux élèves et aux familles s’inscrivent aux côtés d’un plaidoyer fondé sur la recherche, de partenariats communautaires et d’une longue histoire d’éducatrices et éducateurs noirs qui agissent contre les inégalités scolaires." }] }],
    [qbbe], "needs-editorial-review"),
  "about/our-story": page(
    { en: "Our story", fr: "Notre histoire" }, { en: "A community institution shaped by educators.", fr: "Une institution communautaire façonnée par des éducatrices et éducateurs." },
    { en: "QBBE was formed in response to barriers experienced by Black students and families in Quebec’s education system.", fr: "QBBE a été créée en réponse aux obstacles rencontrés par les élèves et les familles noirs dans le système d’éducation québécois." },
    [{ heading: { en: "Why QBBE began", fr: "Pourquoi QBBE a vu le jour" }, paragraphs: [{ en: "QBBE’s history records that a group of concerned Black educators, largely from the Caribbean, came together as English-speaking Black communities confronted cultural and educational barriers in Quebec schools.", fr: "L’histoire de QBBE indique qu’un groupe d’éducatrices et éducateurs noirs, en grande partie originaires des Caraïbes, s’est réuni alors que les communautés noires anglophones faisaient face à des obstacles culturels et éducatifs dans les écoles du Québec." }] }, { heading: { en: "What continues", fr: "Ce qui se poursuit" }, paragraphs: [{ en: "The organization’s public materials connect academic support with family programming, research, advocacy, and opportunities for multicultural and intercultural communities.", fr: "Les documents publics de l’organisation relient le soutien scolaire aux programmes familiaux, à la recherche, au plaidoyer et aux occasions destinées aux communautés multiculturelles et interculturelles." }] }],
    ["https://qbbe.ca/history/", qbbe], "needs-editorial-review"),
  "about/history": page(
    { en: "Since 1968", fr: "Depuis 1968" }, { en: "A history grounded in educational equity.", fr: "Une histoire ancrée dans l’équité en éducation." },
    { en: "QBBE preserves a history of Black educators organizing in response to inequity and the educational needs of their communities.", fr: "QBBE préserve l’histoire d’éducatrices et éducateurs noirs qui se sont organisés en réponse aux inégalités et aux besoins éducatifs de leurs communautés." },
    [{ heading: { en: "Late 1960s: a changing Quebec", fr: "Fin des années 1960 : un Québec en changement" }, paragraphs: [{ en: "QBBE’s history describes increased Caribbean immigration to Quebec in the late 1960s and a school system that was not equipped to address the cultural differences and challenges immigrant children encountered. The source also identifies concerns about Black student achievement and low participation in higher education.", fr: "L’histoire de QBBE décrit l’augmentation de l’immigration caribéenne au Québec à la fin des années 1960 et un système scolaire qui n’était pas équipé pour répondre aux différences culturelles et aux défis rencontrés par les enfants immigrants. La source fait aussi état de préoccupations liées à la réussite des élèves noirs et à leur faible présence dans l’enseignement supérieur." }] }, { heading: { en: "1968: QBBE is formed", fr: "1968 : création de QBBE" }, paragraphs: [{ en: "In response to the educational and social needs of English-speaking Black communities, concerned Black educators, mostly from the Caribbean, founded QBBE. This is QBBE’s stated founding era.", fr: "En réponse aux besoins éducatifs et sociaux des communautés noires anglophones, des éducatrices et éducateurs noirs préoccupés, majoritairement originaires des Caraïbes, ont fondé QBBE. Il s’agit de l’époque de fondation déclarée par QBBE." }] }, { heading: { en: "1971: legal registration", fr: "1971 : enregistrement légal" }, paragraphs: [{ en: "QBBE’s history page states that the organization was legally registered on December 29, 1971.", fr: "La page historique de QBBE indique que l’organisation a été légalement enregistrée le 29 décembre 1971." }] }, { heading: { en: "A continuing community reach", fr: "Un rayonnement communautaire continu" }, paragraphs: [{ en: "QBBE’s public materials describe work with students, families, educators, and multicultural/intercultural communities. No later-decade milestone is published here without a QBBE-owned source.", fr: "Les documents publics de QBBE décrivent un travail auprès des élèves, des familles, des éducatrices et éducateurs, ainsi que des communautés multiculturelles et interculturelles. Aucune étape ultérieure n’est publiée ici sans source appartenant à QBBE." }] }],
    ["https://qbbe.ca/history/"], "needs-editorial-review", "Formal French institutional copy requires approval."),
  "about/mission": page(
    { en: "Mission & vision", fr: "Mission et vision" }, { en: "Educational opportunity must be shared equitably.", fr: "Les possibilités éducatives doivent être partagées équitablement." },
    { en: "QBBE’s formal mission is preserved alongside its vision as a learning and research institution.", fr: "La mission officielle de QBBE est préservée avec sa vision d’institution d’apprentissage et de recherche." },
    [{ heading: { en: "Formal mission", fr: "Mission officielle" }, paragraphs: [{ en: "To encourage and support continuous improvements in the education system of Quebec and the equitable distribution of its benefits to communities of colour, so that programs provide the best opportunity to pursue educational attainment, with resulting social and economic outcomes.", fr: "Encourager et soutenir l’amélioration continue du système d’éducation du Québec et la répartition équitable de ses bénéfices auprès des communautés de couleur, afin que les programmes offrent les meilleures possibilités de réussite éducative et les retombées sociales et économiques qui en découlent." }] }, { heading: { en: "Vision", fr: "Vision" }, paragraphs: [{ en: "QBBE describes itself as a learning and research institution committed to pursuing excellence in educational opportunities for multicultural and intercultural communities.", fr: "QBBE se décrit comme une institution d’apprentissage et de recherche engagée dans la poursuite de l’excellence en matière de possibilités éducatives pour les communautés multiculturelles et interculturelles." }] }, { heading: { en: "Who QBBE serves", fr: "Les personnes que sert QBBE" }, paragraphs: [{ en: "QBBE’s public materials identify elementary and high-school students, families, educators, and multicultural/intercultural communities. The legacy site also refers to English-speaking Black communities; sector-specific service claims need confirmation before publication.", fr: "Les documents publics de QBBE identifient les élèves du primaire et du secondaire, les familles, les éducatrices et éducateurs ainsi que les communautés multiculturelles et interculturelles. Le site historique fait aussi référence aux communautés noires anglophones; les affirmations propres à un secteur scolaire doivent être confirmées avant publication." }] }],
    ["https://qbbe.ca/history/", "https://qbbe.ca/board-of-directors/"], "needs-legal-review", "Formal French wording must be approved by QBBE."),
  "about/leadership": page(
    { en: "Leadership & governance", fr: "Leadership et gouvernance" }, { en: "Governance in service of educational equity.", fr: "Une gouvernance au service de l’équité en éducation." },
    { en: "The legacy site documents board committees and a historic leadership roster. QBBE must confirm the current roster before launch.", fr: "Le site historique présente les comités du conseil et une liste de leadership historique. QBBE doit confirmer la liste actuelle avant le lancement." },
    [{ heading: { en: "Board committees", fr: "Comités du conseil" }, paragraphs: [{ en: "The legacy Board page identifies Governance, Finance, Rebranding, and Education committees. It describes the Education Committee as overseeing educational programming, including Da Costa Hall and BANA summer programs.", fr: "La page historique du conseil identifie les comités de gouvernance, de finances, de rebranding et d’éducation. Elle décrit le comité d’éducation comme responsable des programmes éducatifs, y compris les programmes d’été Da Costa Hall et BANA." }] }, { heading: { en: "Roster confirmation required", fr: "Confirmation de la liste requise" }, paragraphs: [{ en: "The legacy page names Alix Adrien, Nadine Collins, Qaadira De Coteau, Martial Joseph, Jamie Sylvester, Otis L. Delaney, Dr. Clarence Bayne, Dr. Horace Goddard, Curtis George, and Garvin Jeffers. These names are preserved in the migration inventory, not presented as a current board roster until QBBE confirms titles, terms, and consent for biographies and photos.", fr: "La page historique nomme Alix Adrien, Nadine Collins, Qaadira De Coteau, Martial Joseph, Jamie Sylvester, Otis L. Delaney, Dr Clarence Bayne, Dr Horace Goddard, Curtis George et Garvin Jeffers. Ces noms sont préservés dans l’inventaire de migration et ne sont pas présentés comme la liste actuelle du conseil jusqu’à confirmation par QBBE des titres, mandats et consentements relatifs aux biographies et photos." }] }],
    ["https://qbbe.ca/board-of-directors/"], "needs-editorial-review"),
  "about/partners": page(
    { en: "Partners & funders", fr: "Partenaires et bailleurs de fonds" }, { en: "Partnerships should be named with care.", fr: "Les partenariats doivent être nommés avec soin." },
    { en: "QBBE’s legacy homepage visually acknowledges Dawson, BCRC, Concordia, and the Canadian Red Cross. Current relationship status requires confirmation.", fr: "La page d’accueil historique de QBBE reconnaît visuellement Dawson, BCRC, Concordia et la Croix-Rouge canadienne. L’état actuel de ces relations doit être confirmé." },
    [{ heading: { en: "A structured partner record", fr: "Un dossier de partenariat structuré" }, paragraphs: [{ en: "Website 2.0 distinguishes funders, education partners, community partners, corporate partners, program partners, and Allies. This avoids implying that a historical acknowledgement is an active partnership.", fr: "Website 2.0 distingue les bailleurs de fonds, partenaires éducatifs, communautaires, corporatifs, de programme et alliés. Cela évite de présenter une reconnaissance historique comme un partenariat actif." }] }, { heading: { en: "Confirmation before display", fr: "Confirmation avant affichage" }, paragraphs: [{ en: "QBBE should approve each organization’s category, relationship status, logo use, and related programs before a public logo wall or partnership claim is published.", fr: "QBBE doit approuver la catégorie, l’état de la relation, l’utilisation du logo et les programmes associés de chaque organisation avant la publication d’un mur de logos ou d’une affirmation de partenariat." }] }],
    [qbbe, "https://qbbe.ca/partners/"], "needs-editorial-review"),
  "about/contact": page(
    { en: "Contact", fr: "Contact" }, { en: "Speak with QBBE.", fr: "Communiquez avec QBBE." },
    { en: "Use the secure contact form or reach the QBBE office directly.", fr: "Utilisez le formulaire de contact sécurisé ou communiquez directement avec le bureau de QBBE." },
    [{ heading: { en: "Office contact", fr: "Coordonnées du bureau" }, paragraphs: [{ en: "QBBE’s legacy contact page lists 5050 Côte Saint Luc Rd, Montreal, Quebec H3W 2H1; (514) 481-9400; and info@qbbe.ca. It lists Monday to Friday hours from 9 am to 4 pm.", fr: "La page de contact historique de QBBE indique le 5050, chemin de la Côte-Saint-Luc, Montréal (Québec) H3W 2H1; le (514) 481-9400; et info@qbbe.ca. Elle indique des heures du lundi au vendredi, de 9 h à 16 h." }] }],
    ["https://qbbe.ca/contact-2/"], "needs-editorial-review", "Values are centralized in content/organization.ts and require final operational confirmation."),
  impact: page(
    { en: "Impact", fr: "Impact" }, { en: "Educational equity is more than a number.", fr: "L’équité en éducation est plus qu’un chiffre." },
    { en: "QBBE’s impact is expressed through students, families, programs, research, advocacy, and community institutions.", fr: "L’impact de QBBE s’exprime auprès des élèves, des familles, des programmes, de la recherche, du plaidoyer et des institutions communautaires." },
    [{ heading: { en: "Verified reporting", fr: "Rapports vérifiés" }, paragraphs: [{ en: "Website 2.0 does not publish numerical impact metrics until QBBE has approved both the value and its source. Historical program claims are retained with their source records for review.", fr: "Website 2.0 ne publie pas de mesures numériques d’impact avant que QBBE ait approuvé la valeur et sa source. Les affirmations historiques relatives aux programmes sont conservées avec leurs sources aux fins de révision." }] }, { heading: { en: "Where to explore", fr: "Où explorer" }, paragraphs: [{ en: "Read impact stories without fabricated testimonials, review available reports, and explore QBBE’s research and advocacy context.", fr: "Lisez des récits d’impact sans témoignages inventés, consultez les rapports disponibles et explorez le contexte de recherche et de plaidoyer de QBBE." }] }],
    [qbbe], "needs-editorial-review"),
  "impact/stories": page(
    { en: "Impact stories", fr: "Récits d’impact" }, { en: "Community impact, described with care.", fr: "L’impact communautaire, raconté avec soin." },
    { en: "Until QBBE provides approved stories and consented testimonials, this page uses institution-level narrative only.", fr: "Jusqu’à ce que QBBE fournisse des récits approuvés et des témoignages consentis, cette page utilise uniquement un récit institutionnel." },
    [{ heading: { en: "What programs make possible", fr: "Ce que les programmes rendent possible" }, paragraphs: [{ en: "QBBE’s public materials describe academic support, family programming, summer learning, research, and advocacy as connected ways of supporting educational opportunity. Individual names, quotes, and outcomes will only be published with approval and consent.", fr: "Les documents publics de QBBE décrivent le soutien scolaire, les programmes familiaux, l’apprentissage estival, la recherche et le plaidoyer comme des façons interreliées de soutenir les possibilités éducatives. Les noms, citations et résultats individuels ne seront publiés qu’avec approbation et consentement." }] }],
    [qbbe], "needs-editorial-review"),
  "impact/reports": page(
    { en: "Reports", fr: "Rapports" }, { en: "A public record that distinguishes current from historical.", fr: "Un dossier public qui distingue le présent de l’historique." },
    { en: "QBBE’s legacy site identifies a 2020 annual report and a 2000 financial statement. Both are preserved as archival records pending file verification.", fr: "Le site historique de QBBE identifie un rapport annuel 2020 et des états financiers de 2000. Les deux sont préservés comme dossiers d’archives en attente de vérification des fichiers." },
    [{ heading: { en: "Publication standard", fr: "Norme de publication" }, paragraphs: [{ en: "Current documents will be added only with their verified file, language, year, description, and approval status. Older documents remain accessible through an archive rather than being removed.", fr: "Les documents actuels seront ajoutés uniquement avec leur fichier vérifié, leur langue, leur année, leur description et leur état d’approbation. Les documents plus anciens demeurent accessibles dans des archives plutôt que d’être supprimés." }] }],
    ["https://qbbe.ca/reports/2020-annual-report/", "https://qbbe.ca/reports/2000-financial-statement/"], "needs-editorial-review"),
  "impact/research": page(
    { en: "Research", fr: "Recherche" }, { en: "Research informs equitable educational practice.", fr: "La recherche éclaire des pratiques éducatives équitables." },
    { en: "QBBE’s public materials frame research as part of work addressing educational bias and improving outcomes for Black and racialized communities.", fr: "Les documents publics de QBBE présentent la recherche comme une partie du travail visant les préjugés en éducation et l’amélioration des résultats pour les communautés noires et racialisées." },
    [{ heading: { en: "Research-informed action", fr: "Une action éclairée par la recherche" }, paragraphs: [{ en: "The legacy site calls for a research incubator and resource centre dedicated to evidence-based research and educational best practices affecting Black and racialized communities. Website 2.0 does not claim a functioning database or current research program until QBBE confirms it.", fr: "Le site historique appelle à la création d’un incubateur de recherche et d’un centre de ressources consacrés à la recherche fondée sur des données probantes et aux pratiques éducatives touchant les communautés noires et racialisées. Website 2.0 ne prétend pas qu’une base de données ou un programme de recherche est actuellement en activité sans confirmation de QBBE." }] }],
    [qbbe], "needs-editorial-review"),
  "impact/advocacy": page(
    { en: "Advocacy", fr: "Plaidoyer" }, { en: "Equity requires representation and action.", fr: "L’équité exige représentation et action." },
    { en: "QBBE’s founding history and public materials connect educational support with advocacy on educational inequality.", fr: "L’histoire fondatrice et les documents publics de QBBE relient le soutien scolaire au plaidoyer contre les inégalités en éducation." },
    [{ heading: { en: "A historic role", fr: "Un rôle historique" }, paragraphs: [{ en: "The legacy FAQ describes QBBE as providing educational support and lobbying school boards and government to eliminate inequalities in education. The organization’s public identity also includes raising awareness of educational bias.", fr: "La FAQ historique décrit QBBE comme un organisme qui offre du soutien éducatif et fait du lobbying auprès des commissions scolaires et des gouvernements afin d’éliminer les inégalités en éducation. L’identité publique de l’organisation comprend aussi la sensibilisation aux préjugés en éducation." }] }, { heading: { en: "Current activity", fr: "Activité actuelle" }, paragraphs: [{ en: "Specific campaigns, policy positions, or current government engagements will be added only when sourced and approved by QBBE.", fr: "Les campagnes précises, positions politiques ou engagements gouvernementaux actuels ne seront ajoutés que lorsqu’ils seront sourcés et approuvés par QBBE." }] }],
    [qbbe, "https://qbbe.ca/board-of-directors/"], "needs-editorial-review"),
  "impact/financial-transparency": page(
    { en: "Financial transparency", fr: "Transparence financière" }, { en: "Records should be clear, current, and contextual.", fr: "Les dossiers doivent être clairs, actuels et contextualisés." },
    { en: "The legacy site links a 2000 financial statement. Current statements, charity information, and tax language require QBBE finance review before publication.", fr: "Le site historique renvoie à des états financiers de 2000. Les états actuels, les renseignements sur l’organisme de bienfaisance et le langage fiscal doivent être examinés par les finances de QBBE avant publication." },
    [{ heading: { en: "What will be published", fr: "Ce qui sera publié" }, paragraphs: [{ en: "Website 2.0 supports current financial statements and historical archives, each with a year, file, description, language, and publication status. It does not infer charitable registration or tax-receipt eligibility from legacy donation pages.", fr: "Website 2.0 prend en charge les états financiers actuels et les archives historiques, chacun avec une année, un fichier, une description, une langue et un état de publication. Il ne déduit pas l’enregistrement à titre d’organisme de bienfaisance ni l’admissibilité aux reçus fiscaux à partir des anciennes pages de dons." }] }],
    ["https://qbbe.ca/reports/2000-financial-statement/", "https://qbbe.ca/donate/"], "needs-legal-review"),
  resources: page(
    { en: "Resources", fr: "Ressources" }, { en: "Knowledge for students, families, educators, and communities.", fr: "Des connaissances pour les élèves, les familles, les éducatrices et éducateurs, et les communautés." },
    { en: "Explore research context, publications, FAQs, and resources that support educational opportunity.", fr: "Explorez le contexte de recherche, les publications, les FAQ et les ressources qui soutiennent les possibilités éducatives." },
    [{ heading: { en: "How this library works", fr: "Fonctionnement de cette bibliothèque" }, paragraphs: [{ en: "Resources are organized by purpose, with publication status and source traceability. Unverified or expired materials are withheld from public download and listed for editorial review.", fr: "Les ressources sont organisées par objectif, avec un état de publication et une traçabilité des sources. Les documents non vérifiés ou expirés sont retirés du téléchargement public et indiqués pour révision éditoriale." }] }],
    [qbbe], "needs-editorial-review"),
  "resources/research": page(
    { en: "Research resources", fr: "Ressources de recherche" }, { en: "A library built for evidence-informed practice.", fr: "Une bibliothèque conçue pour une pratique éclairée par les données." },
    { en: "This is the public resource-library layer of QBBE’s research architecture.", fr: "Il s’agit de la couche de bibliothèque de ressources publiques de l’architecture de recherche de QBBE." },
    [{ heading: { en: "Available content", fr: "Contenu disponible" }, paragraphs: [{ en: "No functioning research database is claimed. QBBE can add approved research links, resource-centre materials, and research opportunities here with an owner, review date, language status, and source.", fr: "Aucune base de données de recherche fonctionnelle n’est revendiquée. QBBE peut ajouter ici des liens de recherche approuvés, des documents du centre de ressources et des occasions de recherche avec une personne responsable, une date de révision, un état linguistique et une source." }] }],
    [qbbe], "needs-editorial-review"),
  "resources/publications": page(
    { en: "Publications", fr: "Publications" }, { en: "Published QBBE materials, with their context intact.", fr: "Des documents publiés par QBBE, avec leur contexte préservé." },
    { en: "Reports and publications are maintained as structured records rather than unlabelled downloads.", fr: "Les rapports et publications sont maintenus comme des dossiers structurés plutôt que comme des téléchargements non étiquetés." },
    [{ heading: { en: "Historical publications", fr: "Publications historiques" }, paragraphs: [{ en: "The migration inventory preserves legacy annual-report and financial-statement records. Their files, descriptions, and access links require verification before publication.", fr: "L’inventaire de migration préserve les dossiers historiques de rapports annuels et d’états financiers. Leurs fichiers, descriptions et liens d’accès doivent être vérifiés avant publication." }] }],
    ["https://qbbe.ca/reports/2020-annual-report/", "https://qbbe.ca/reports/2000-financial-statement/"], "needs-editorial-review"),
  "resources/parents": page(
    { en: "For parents & guardians", fr: "Pour les parents et tutrices ou tuteurs" }, { en: "Practical support for your child’s learning journey.", fr: "Un soutien pratique pour le parcours d’apprentissage de votre enfant." },
    { en: "QBBE’s Family First and academic programs connect school support with family well-being and practical guidance.", fr: "Les programmes La famille d’abord et de soutien scolaire de QBBE relient le soutien à l’école au bien-être familial et à des conseils pratiques." },
    [{ heading: { en: "Start here", fr: "Commencez ici" }, paragraphs: [{ en: "Explore Family First for workshop themes including school support and communication, or review program pages for current registration and eligibility information. Contact QBBE when a program cycle is marked for confirmation.", fr: "Explorez La famille d’abord pour les thèmes d’ateliers, notamment le soutien scolaire et la communication, ou consultez les pages des programmes pour obtenir des renseignements sur les inscriptions et l’admissibilité. Communiquez avec QBBE lorsqu’un cycle de programme est marqué à confirmer." }] }],
    ["https://qbbe.ca/family-first-program/"], "needs-program-review"),
  "resources/students": page(
    { en: "For students", fr: "Pour les élèves" }, { en: "Support, skills, and pathways forward.", fr: "Du soutien, des compétences et des parcours vers l’avenir." },
    { en: "QBBE’s program record includes academic support, summer learning, career exploration, and transition-focused content.", fr: "Le dossier de programmes de QBBE comprend du soutien scolaire, de l’apprentissage estival, l’exploration de carrières et du contenu axé sur les transitions." },
    [{ heading: { en: "Choose the right program", fr: "Choisir le bon programme" }, paragraphs: [{ en: "Use the program finder to explore offerings by need. Da Costa Hall is currently listed on the QBBE student portal for summer 2026 registration; other cycles are clearly marked when they require confirmation.", fr: "Utilisez le chercheur de programmes pour explorer les offres selon vos besoins. Da Costa Hall est actuellement indiqué sur le portail étudiant QBBE pour les inscriptions de l’été 2026; les autres cycles sont clairement marqués lorsqu’ils doivent être confirmés." }] }],
    ["https://student.qbbe.ca/"], "needs-program-review"),
  "resources/educators": page(
    { en: "For educators", fr: "Pour les éducatrices et éducateurs" }, { en: "Education expertise in conversation with community.", fr: "Une expertise éducative en dialogue avec la communauté." },
    { en: "QBBE was founded by Black educators and identifies learning, research, advocacy, and educational opportunity as connected work.", fr: "QBBE a été fondée par des éducatrices et éducateurs noirs et présente l’apprentissage, la recherche, le plaidoyer et les possibilités éducatives comme un travail interrelié." },
    [{ heading: { en: "How to engage", fr: "Comment s’engager" }, paragraphs: [{ en: "Educators can explore QBBE’s research and advocacy context, become an Ally, or use the contact form to ask about partnerships and volunteer opportunities. Current opportunities should be confirmed directly with QBBE.", fr: "Les éducatrices et éducateurs peuvent explorer le contexte de recherche et de plaidoyer de QBBE, devenir alliés ou utiliser le formulaire de contact pour se renseigner sur les partenariats et le bénévolat. Les occasions actuelles doivent être confirmées directement auprès de QBBE." }] }],
    ["https://qbbe.ca/history/"], "needs-editorial-review"),
  "resources/faq": page(
    { en: "Frequently asked questions", fr: "Foire aux questions" }, { en: "Clear answers, with clear limits.", fr: "Des réponses claires, avec des limites claires." },
    { en: "QBBE’s legacy FAQ has been consolidated into a reviewed content model. Financial and tax questions remain clearly marked for confirmation.", fr: "La FAQ historique de QBBE a été consolidée dans un modèle de contenu révisé. Les questions financières et fiscales demeurent clairement indiquées pour confirmation." },
    [{ heading: { en: "Need help now?", fr: "Besoin d’aide maintenant?" }, paragraphs: [{ en: "The legacy FAQ lists (514) 481-9400 and info@qbbe.ca. Use the contact page for centralized details and to ask about a current program cycle.", fr: "La FAQ historique indique le (514) 481-9400 et info@qbbe.ca. Utilisez la page de contact pour obtenir les coordonnées centralisées et vous renseigner sur un cycle de programme actuel." }] }],
    ["https://qbbe.ca/faqs/"], "needs-editorial-review"),
  "resources/anti-racism-support": page(
    { en: "Anti-racism support", fr: "Soutien contre le racisme" }, { en: "Service status requires confirmation.", fr: "L’état du service doit être confirmé." },
    { en: "The QBBE legacy homepage references an Anti-Racism Hotline, but public details could not be verified during this migration.", fr: "La page d’accueil historique de QBBE fait référence à une ligne d’aide contre le racisme, mais les détails publics n’ont pas pu être vérifiés pendant cette migration." },
    [{ heading: { en: "Before publishing a hotline", fr: "Avant de publier une ligne d’aide" }, paragraphs: [{ en: "QBBE must confirm whether the service is active, its scope, contact details, hours, privacy expectations, limitations, and any emergency guidance. This page intentionally does not present unverified contact information.", fr: "QBBE doit confirmer si le service est actif, sa portée, ses coordonnées, ses heures, les attentes en matière de confidentialité, ses limites et toute consigne d’urgence. Cette page ne présente intentionnellement aucune coordonnée non vérifiée." }] }],
    [qbbe], "needs-editorial-review", "Do not publish a hotline number until QBBE confirms the service."),
  "resources/archived-initiatives": page(
    { en: "Institutional archive", fr: "Archives institutionnelles" }, { en: "Historic initiatives, retained with context.", fr: "Des initiatives historiques, conservées avec leur contexte." },
    { en: "These QBBE initiatives are preserved as historical records. Their inclusion here does not mean they are currently accepting participants, offering the same curriculum, or using the same funding arrangements.", fr: "Ces initiatives de QBBE sont conservées comme documents historiques. Leur présence ici ne signifie pas qu’elles accueillent actuellement des participants, offrent le même programme ou utilisent les mêmes modalités de financement." },
    [
      { heading: { en: "Parenting Skills Support Program (PSSP)", fr: "Programme de soutien aux compétences parentales (PSSP)" }, paragraphs: [{ en: "A legacy QBBE page describes free biweekly workshops and focus groups that supported parenting skills and helping children at school. Recorded themes include parenting, home management, financial literacy, school governance, vocational training, and Quebec history and culture. The page acknowledges Réseau réussite Montréal as funder.", fr: "Une page historique de QBBE décrit des ateliers et groupes de discussion gratuits toutes les deux semaines visant les compétences parentales et le soutien des enfants à l’école. Les thèmes indiqués comprennent la parentalité, la gestion du foyer, la littératie financière, la gouvernance scolaire, la formation professionnelle ainsi que l’histoire et la culture du Québec. La page reconnaît Réseau réussite Montréal comme bailleur de fonds." }] },
      { heading: { en: "Self-Elevation Project (SEP)", fr: "Projet d’autoélévation (SEP)" }, paragraphs: [{ en: "The legacy Self-Elevation Project describes a workshop series focused on parenting-related issues. Its recorded themes include communication, mental health, managing emotions, supporting children at school, self-empowerment, cyberbullying, employment, and entrepreneurship. The page thanks Sommet Jeunes Afro (SDESJ) and Ville de Montréal, and identifies the project as part of the Support for Black Families Program.", fr: "Le projet historique d’autoélévation décrit une série d’ateliers sur des questions liées à la parentalité. Les thèmes recensés comprennent la communication, la santé mentale, la gestion des émotions, le soutien des enfants à l’école, l’autonomisation, la cyberintimidation, l’emploi et l’entrepreneuriat. La page remercie Sommet Jeunes Afro (SDESJ) et la Ville de Montréal, et présente le projet comme faisant partie du programme de soutien aux familles noires." }] },
      { heading: { en: "Entrepreneurship, leadership & personal development", fr: "Entrepreneuriat, leadership et développement personnel" }, paragraphs: [{ en: "The legacy program page preserves Financial Literacy and STEAM as planned components. It discusses personal financial management, budgeting, investing, responsible debt use, education savings, business financial knowledge, and interdisciplinary STEAM learning. The page said both programs were under construction for Spring 2022, so Website 2.0 does not describe them as active.", fr: "La page historique du programme conserve la littératie financière et les STIAM comme composantes prévues. Elle aborde la gestion financière personnelle, le budget, l’investissement, l’utilisation responsable du crédit, l’épargne-études, les connaissances financières en affaires et l’apprentissage interdisciplinaire STIAM. La page indiquait que les deux programmes étaient en construction pour le printemps 2022; Website 2.0 ne les présente donc pas comme actifs." }] },
      { heading: { en: "What happens next", fr: "Prochaines étapes" }, paragraphs: [{ en: "QBBE can reactivate an initiative only after its program owner confirms the current curriculum, delivery format, eligibility, consent requirements, dates, fees, and funding acknowledgement. Until then, these records protect institutional knowledge without publishing an obsolete offer.", fr: "QBBE ne peut réactiver une initiative qu’après confirmation par la personne responsable du programme du curriculum actuel, du format, des critères d’admissibilité, des exigences de consentement, des dates, des frais et de la reconnaissance du financement. Entre-temps, ces dossiers préservent la mémoire institutionnelle sans publier une offre périmée." }] },
    ],
    ["https://qbbe.ca/pssp/", "https://qbbe.ca/sep/", "https://qbbe.ca/programs/entrepreneurship-leadership-program/"], "needs-program-review", "All content on this page is historical context recovered from QBBE-owned legacy pages."),
  "impact/youth-empowerment": page(
    { en: "Youth empowerment", fr: "Autonomisation des jeunes" }, { en: "A strategic theme, not an unverified program.", fr: "Un thème stratégique, et non un programme non vérifié." },
    { en: "QBBE’s legacy homepage frames youth empowerment as creating a future where students have opportunities to succeed through learning opportunities and literacy resources.", fr: "La page d’accueil historique de QBBE présente l’autonomisation des jeunes comme la création d’un avenir où les élèves ont la possibilité de réussir grâce à des occasions d’apprentissage et à des ressources en littératie." },
    [{ heading: { en: "How it appears in the work", fr: "Comment cela se manifeste dans le travail" }, paragraphs: [{ en: "Website 2.0 treats youth empowerment as an institutional theme across academic support, literacy, summer learning, high-school transition, career exploration, and family support. It is not presented as a standalone current program because QBBE’s public source did not establish one.", fr: "Website 2.0 traite l’autonomisation des jeunes comme un thème institutionnel qui traverse le soutien scolaire, la littératie, l’apprentissage estival, la transition vers le secondaire, l’exploration de carrières et le soutien aux familles. Elle n’est pas présentée comme un programme actuel autonome, car la source publique de QBBE n’en établit pas un." }] }],
    [qbbe], "needs-editorial-review"),
  "get-involved": page(
    { en: "Get involved", fr: "S’impliquer" }, { en: "Bring your time, expertise, resources, or organization.", fr: "Offrez votre temps, votre expertise, vos ressources ou votre organisation." },
    { en: "QBBE’s work is strengthened by volunteers, educators, partners, donors, and Allies.", fr: "Le travail de QBBE est renforcé par les bénévoles, les éducatrices et éducateurs, les partenaires, les donatrices et donateurs ainsi que les alliés." },
    [{ heading: { en: "Choose your path", fr: "Choisissez votre voie" }, paragraphs: [{ en: "Volunteer through the legacy Colibri program record, explore educator and partnership pathways, make a donation, or learn about QBBE Ally membership. Each current opportunity should have a named QBBE owner before launch.", fr: "Faites du bénévolat par l’entremise du dossier historique du programme Colibri, explorez les voies destinées aux éducatrices et éducateurs et aux partenaires, faites un don ou découvrez l’adhésion Allié QBBE. Chaque occasion actuelle doit avoir une personne responsable désignée par QBBE avant le lancement." }] }],
    ["https://qbbe.ca/volunteers/", qbbe], "needs-editorial-review"),
  "get-involved/volunteer": page(
    { en: "Volunteer", fr: "Bénévolat" }, { en: "One Drop at a Time.", fr: "Une goutte à la fois." },
    { en: "QBBE’s legacy Colibri Volunteer Program presents volunteerism as a community practice rooted in integrity, compassion, teamwork, volunteerism, and excellence.", fr: "Le programme historique de bénévolat Colibri de QBBE présente le bénévolat comme une pratique communautaire ancrée dans l’intégrité, la compassion, le travail d’équipe, le bénévolat et l’excellence." },
    [{ heading: { en: "Colibri Volunteer Program", fr: "Programme de bénévolat Colibri" }, paragraphs: [{ en: "The legacy program’s mission is to provide resources for children’s and communities’ immediate developmental needs and build systems that strengthen existing structures through sustainable community development. Its vision is to develop life skills and academic competencies for marginalized and minority students.", fr: "La mission du programme historique est d’offrir des ressources pour les besoins de développement immédiats des enfants et des communautés et de bâtir des systèmes qui renforcent les structures existantes par un développement communautaire durable. Sa vision vise à développer les compétences de la vie courante et les compétences scolaires des élèves marginalisés et issus de minorités." }] }, { heading: { en: "Current opportunities", fr: "Occasions actuelles" }, paragraphs: [{ en: "The application form captures interest only until QBBE confirms current roles, screening requirements, schedules, privacy language, and a volunteer contact.", fr: "Le formulaire de candidature recueille uniquement les manifestations d’intérêt jusqu’à ce que QBBE confirme les rôles actuels, les exigences de sélection, les horaires, la formulation de confidentialité et une personne-ressource pour le bénévolat." }] }],
    ["https://qbbe.ca/volunteers/"], "needs-program-review", "Confirm whether Colibri remains the approved volunteer-program name."),
  "get-involved/educators": page(
    { en: "For educators", fr: "Pour les éducatrices et éducateurs" }, { en: "Share knowledge. Strengthen opportunity.", fr: "Partagez vos connaissances. Renforcez les possibilités." },
    { en: "QBBE’s founding story places educators at the centre of community action for educational equity.", fr: "L’histoire fondatrice de QBBE place les éducatrices et éducateurs au centre de l’action communautaire pour l’équité en éducation." },
    [{ heading: { en: "Ways to connect", fr: "Façons de contribuer" }, paragraphs: [{ en: "Use this route to express interest in educational partnerships, program support, or volunteering. Specific roles and professional-development opportunities will be published only when QBBE confirms them.", fr: "Utilisez cette page pour manifester votre intérêt envers les partenariats éducatifs, le soutien aux programmes ou le bénévolat. Les rôles précis et les occasions de perfectionnement professionnel ne seront publiés que lorsque QBBE les aura confirmés." }] }],
    ["https://qbbe.ca/history/"], "needs-program-review"),
  "get-involved/corporate-partners": page(
    { en: "Corporate partners", fr: "Partenaires corporatifs" }, { en: "Build opportunity with QBBE.", fr: "Bâtissez des possibilités avec QBBE." },
    { en: "QBBE’s legacy materials describe corporate awareness, sponsorship, and partnerships that strengthen educational programming.", fr: "Les documents historiques de QBBE décrivent la sensibilisation du milieu corporatif, le parrainage et les partenariats qui renforcent la programmation éducative." },
    [{ heading: { en: "Start a conversation", fr: "Entamer une conversation" }, paragraphs: [{ en: "Use the partner enquiry form to discuss a potential corporate relationship. No partner is represented as current until QBBE approves its relationship status and public acknowledgement.", fr: "Utilisez le formulaire de demande de partenariat pour discuter d’une relation corporative potentielle. Aucun partenaire n’est présenté comme actuel avant que QBBE approuve l’état de la relation et la reconnaissance publique." }] }],
    [qbbe], "needs-editorial-review"),
  "get-involved/community-partners": page(
    { en: "Community partners", fr: "Partenaires communautaires" }, { en: "Community institutions make collective work possible.", fr: "Les institutions communautaires rendent le travail collectif possible." },
    { en: "QBBE’s history describes collaboration with communities, families, educators, and organizations working toward educational equity.", fr: "L’histoire de QBBE décrit une collaboration avec les communautés, les familles, les éducatrices et éducateurs ainsi que les organisations qui travaillent pour l’équité en éducation." },
    [{ heading: { en: "Work together", fr: "Travailler ensemble" }, paragraphs: [{ en: "Use the partner enquiry form to explore a community collaboration. QBBE will determine fit, safeguarding requirements, ownership, and acknowledgement before an initiative is publicized.", fr: "Utilisez le formulaire de demande de partenariat pour explorer une collaboration communautaire. QBBE déterminera la pertinence, les exigences de protection, la responsabilité et la reconnaissance avant qu’une initiative soit rendue publique." }] }],
    [qbbe], "needs-editorial-review"),
};
