import type { Program } from "./types";

const migrated = "2026-08-17";
const source = (sourceUrls: string[], verificationStatus: Program["meta"]["verificationStatus"], notes?: string) => ({ sourceUrls, migratedAt: migrated, migratedBy: "Website 2.0 migration", verificationStatus, notes, translation: { en: "needs-review", fr: "needs-review" } } as const);

export const programs: Program[] = [
  {
    slug: "academic-support",
    title: { en: "Academic Support", fr: "Soutien scolaire" },
    summary: { en: "Tutoring and academic support for students, with current delivery details confirmed through QBBE registration.", fr: "Tutorat et soutien scolaire pour les élèves; les modalités actuelles sont confirmées par l’inscription QBBE." },
    audience: ["student", "parent"], needs: ["academic"],
    status: { en: "Current details available from QBBE", fr: "Détails actuels disponibles auprès de QBBE" },
    format: { en: "In-person tutoring is listed on the current registration portal", fr: "Le portail d’inscription indique du tutorat en personne" },
    schedule: { en: "Confirm the current cycle with QBBE", fr: "Confirmez la session actuelle auprès de QBBE" },
    fullDescription: [
      { en: "QBBE lists Academic Support through its student registration portal. The portal currently identifies in-person tutoring at the QBBE Learning Center.", fr: "QBBE présente le soutien scolaire sur son portail d’inscription. Le portail indique actuellement du tutorat en personne au Centre d’apprentissage QBBE." },
      { en: "The 2024 Fall Academic Support page lists elementary Math, English, and French, and high-school Math (CST and SN), English, French, Science, and History. These are preserved as a historical course record, not as a current guarantee.", fr: "La page de soutien scolaire de l’automne 2024 indique les mathématiques, l’anglais et le français au primaire, ainsi que les mathématiques (CST et SN), l’anglais, le français, les sciences et l’histoire au secondaire. Ces renseignements sont conservés comme dossier historique, et non comme une garantie actuelle." },
    ],
    sections: [{ heading: { en: "What is confirmed", fr: "Ce qui est confirmé" }, paragraphs: [{ en: "The current registration portal identifies Academic Support and lists an in-person tutoring start date and QBBE Learning Center location. QBBE’s 2024 source also documents the course range offered in that cycle.", fr: "Le portail d’inscription actuel présente le soutien scolaire, une date de début du tutorat en personne et le Centre d’apprentissage QBBE. La source 2024 de QBBE documente aussi la gamme de cours offerte pendant ce cycle." }] }],
    registrationUrl: "https://student.qbbe.ca/", relatedPrograms: ["da-costa-hall", "early-literacy"],
    meta: source(["https://student.qbbe.ca/", "https://qbbe.ca/programs/academic-support/"], "needs-program-review", "2024 subjects are preserved as historical context. Do not publish a grade range, recurring schedule, or current course availability until QBBE confirms the 2026 cycle."),
  },
  {
    slug: "early-literacy",
    title: { en: "Early Literacy", fr: "Alphabétisation précoce" },
    summary: { en: "Early intervention focused on literacy, reading and comprehension in an inclusive learning environment.", fr: "Intervention précoce axée sur l’alphabétisation, la lecture et la compréhension dans un milieu d’apprentissage inclusif." },
    audience: ["student", "parent"], needs: ["literacy", "academic"],
    age: { en: "Under age five on the 2024 program page", fr: "Moins de cinq ans sur la page de programme de 2024" },
    status: { en: "Program details under QBBE review", fr: "Détails du programme en révision par QBBE" },
    fullDescription: [{ en: "QBBE’s February 2024 Early Literacy Program page says the program was created for children under age five to develop fluent reading through literacy activities. It describes reading and comprehension, a welcoming, safe, inclusive environment, and nutritious snacks.", fr: "La page du programme d’alphabétisation précoce de QBBE, datée de février 2024, indique que le programme a été créé pour les enfants de moins de cinq ans afin de développer une lecture fluide par des activités d’alphabétisation. Elle décrit la lecture et la compréhension, un environnement accueillant, sûr et inclusif, ainsi que des collations nutritives." }],
    sections: [{ heading: { en: "Historical program record", fr: "Dossier historique du programme" }, paragraphs: [{ en: "The 2024 page listed Saturday sessions from 10 am to noon and membership-included registration. These details are historical and intentionally not presented as the current schedule or fee.", fr: "La page de 2024 indiquait des séances le samedi de 10 h à midi et une inscription incluse dans l’adhésion. Ces détails sont historiques et ne sont volontairement pas présentés comme l’horaire ou les frais actuels." }] }],
    relatedPrograms: ["academic-support", "bana"], meta: source(["https://qbbe.ca/programs/early-literacy-program/"], "needs-program-review", "Accessible through QBBE’s public WordPress API. The 2024 source supports an under-five age statement only for that historic cycle; current operations require confirmation."),
  },
  {
    slug: "future-careers",
    title: { en: "Future Careers", fr: "Métiers de l’avenir" },
    summary: { en: "A QBBE initiative describing practical, transferable skills for young people entering evolving career sectors.", fr: "Une initiative QBBE qui présente des compétences pratiques et transférables pour les jeunes qui se dirigent vers des secteurs en évolution." },
    audience: ["student"], needs: ["career", "technology"], age: { en: "Ages 16–25 on the legacy page", fr: "16 à 25 ans sur la page historique" },
    status: { en: "Requires confirmation before accepting registrations", fr: "Confirmation requise avant d’accepter des inscriptions" },
    fullDescription: [{ en: "The legacy page describes a Future Careers initiative for young people aged 16 to 25, focused on practical and transferable skills in high-demand technological fields, including cybersecurity. QBBE must confirm whether this initiative is currently active and which training partners, courses, dates, and eligibility rules apply.", fr: "La page historique décrit une initiative Métiers de l’avenir destinée aux jeunes de 16 à 25 ans et axée sur des compétences pratiques et transférables dans des domaines technologiques recherchés, dont la cybersécurité. QBBE doit confirmer si l’initiative est active ainsi que les partenaires, cours, dates et critères applicables." }],
    sections: [{ heading: { en: "Before launch", fr: "Avant le lancement" }, paragraphs: [{ en: "No salary, completion-time, employer, or course promise is published here because those details have not been verified for the current program cycle.", fr: "Aucune promesse de salaire, de durée, d’employeur ou de cours n’est publiée ici puisque ces détails n’ont pas été vérifiés pour le cycle actuel." }] }],
    meta: source(["https://qbbe.ca/programs/future-careers/"], "needs-program-review", "Legacy content describes a 6-month pathway and salary estimate; do not reproduce either as a current claim."),
  },
  {
    slug: "family-first",
    title: { en: "Family First", fr: "La famille d’abord" },
    summary: { en: "Interactive workshops that support parents, children and teens while strengthening family relationships and practical life skills.", fr: "Des ateliers interactifs qui soutiennent les parents, les enfants et les adolescents tout en renforçant les relations familiales et les compétences de la vie courante." },
    audience: ["parent", "student", "community"], needs: ["family"],
    status: { en: "Confirm the next workshop series with QBBE", fr: "Confirmez la prochaine série d’ateliers auprès de QBBE" },
    fullDescription: [{ en: "QBBE’s Family First Program is designed to support parents, children, and teens through interactive workshops that strengthen family relationships, build practical life skills, and promote well-being.", fr: "Le programme La famille d’abord de QBBE est conçu pour soutenir les parents, les enfants et les adolescents par des ateliers interactifs qui renforcent les relations familiales, développent des compétences pratiques et favorisent le bien-être." }],
    sections: [{ heading: { en: "Workshop themes", fr: "Thèmes des ateliers" }, paragraphs: [{ en: "QBBE identifies school support, effective communication, conflict resolution, mental-health awareness, immigration guidance, career exploration, bullying and cyberbullying prevention, and self-development.", fr: "QBBE identifie le soutien scolaire, la communication efficace, la résolution de conflits, la sensibilisation à la santé mentale, l’orientation en immigration, l’exploration de carrière, la prévention de l’intimidation et de la cyberintimidation, ainsi que le développement personnel." }] }],
    meta: source(["https://qbbe.ca/family-first-program/"], "needs-program-review", "A January 2026 start date was past at migration time and is intentionally not treated as current."),
  },
  {
    slug: "learn-to-code",
    title: { en: "Learn to Code", fr: "Apprendre à coder" },
    summary: { en: "A QBBE learning offer that introduces coding and computer science through hands-on, project-based activity.", fr: "Une offre d’apprentissage QBBE qui initie au codage et à l’informatique par des activités pratiques axées sur des projets." },
    audience: ["student", "educator"], needs: ["technology"], age: { en: "Ages 8–16 on the legacy page", fr: "8 à 16 ans sur la page historique" },
    status: { en: "Interest only until QBBE confirms a new cycle", fr: "Manifestation d’intérêt seulement jusqu’à confirmation d’une nouvelle session" },
    fullDescription: [{ en: "The legacy Learn to Code page describes an engaging introduction to coding fundamentals and computer science for children aged 8 to 16, with hands-on projects, interactive activities, and instructor guidance. It also says weekday and weekend classes were anticipated.", fr: "La page historique Apprendre à coder décrit une initiation attrayante aux bases du codage et de l’informatique pour les enfants de 8 à 16 ans, avec des projets pratiques, des activités interactives et l’encadrement d’une personne enseignante. Elle indique aussi que des cours de semaine et de fin de semaine étaient envisagés." }],
    sections: [{ heading: { en: "Current status", fr: "État actuel" }, paragraphs: [{ en: "The source page contains a 2024 start reference and an undetermined fee. This site preserves the program knowledge but does not present those details as current.", fr: "La page source contient une référence à un début en 2024 et des frais à déterminer. Le présent site préserve la connaissance du programme sans présenter ces détails comme actuels." }] }],
    meta: source(["https://qbbe.ca/learn-to-code/"], "needs-program-review", "Confirm age range, cycle, fees, instructor availability, and whether the waitlist remains active."),
  },
  {
    slug: "bana",
    title: { en: "BANA Summer Day Camp", fr: "Camp de jour d’été BANA" },
    summary: { en: "A summer day-camp model combining morning academics with afternoon recreation, arts, culture, music, and outings.", fr: "Un modèle de camp de jour estival qui combine des activités académiques le matin et des loisirs, arts, activités culturelles, musique et sorties l’après-midi." },
    audience: ["student", "parent"], needs: ["literacy", "academic", "mentorship"], age: { en: "Ages 6–14 on the 2025 page", fr: "6 à 14 ans sur la page de 2025" },
    status: { en: "2025 details archived; confirm the next summer cycle", fr: "Détails de 2025 archivés; confirmez le prochain cycle estival" },
    fullDescription: [{ en: "QBBE’s 2025 BANA page describes a summer day camp with morning academic learning in French, English, and Math, and afternoon sports, recreation, arts and crafts, cultural outings, and music. It identifies the QBBE Learning Center as the location and says daycare and subsidy support may be available upon request.", fr: "La page BANA 2025 de QBBE décrit un camp de jour estival avec des activités académiques le matin en français, anglais et mathématiques, et des sports, loisirs, arts plastiques, sorties culturelles et musique l’après-midi. Elle indique le Centre d’apprentissage QBBE comme lieu et précise qu’un service de garde et du soutien par subvention peuvent être disponibles sur demande." }],
    sections: [{ heading: { en: "Historical context", fr: "Contexte historique" }, paragraphs: [{ en: "QBBE states that the BANA and Da Costa Hall summer-school programs have served more than 15,000 students since their inception in 1968. This historical impact claim needs editorial approval before it appears as a public metric.", fr: "QBBE indique que les programmes d’été BANA et Da Costa Hall ont servi plus de 15 000 élèves depuis leur création en 1968. Cette affirmation d’impact historique doit être approuvée avant d’apparaître comme une mesure publique." }] }],
    relatedPrograms: ["da-costa-hall", "early-literacy"], meta: source(["https://qbbe.ca/programs/the-bana-program-2/"], "needs-program-review", "Dates, pricing, member pricing, age range, daycare, subsidy, and Jam Vocal reference are from the 2025 page and must not be treated as current."),
  },
  {
    slug: "da-costa-hall",
    title: { en: "Da Costa Hall", fr: "Da Costa Hall" },
    summary: { en: "A secondary remedial summer-school and academic-support program for students working toward course credits and graduation requirements.", fr: "Un programme d’été de rattrapage et de soutien scolaire au secondaire pour les élèves qui travaillent à l’obtention de crédits et aux exigences de diplomation." },
    audience: ["student", "parent"], needs: ["academic"], gradeRange: { en: "Grades 7–11 on the legacy page", fr: "Secondaire 1 à 5 sur la page historique" },
    status: { en: "Summer 2026 registration is listed on the QBBE student portal", fr: "Les inscriptions pour l’été 2026 sont indiquées sur le portail étudiant QBBE" },
    fullDescription: [{ en: "Da Costa Hall provides academic enrichment, remediation, tutoring, and an opportunity for at-risk high-school students to take remedial courses or write supplemental exams needed to obtain prerequisite credits for graduation.", fr: "Da Costa Hall offre de l’enrichissement, du rattrapage, du tutorat et la possibilité pour les élèves du secondaire à risque de suivre des cours de reprise ou de passer des examens de reprise afin d’obtenir les crédits préalables à la diplomation." }],
    sections: [{ heading: { en: "Courses described by QBBE", fr: "Cours décrits par QBBE" }, paragraphs: [{ en: "For Grades 7 to 9, the legacy page lists Math, English, French, and Grade 9 History. For Grades 10 and 11, it lists bridge/upgrading courses in Math and Science and supplemental exams leading to graduation. Confirm the current course list during registration.", fr: "Pour le secondaire 1 à 3, la page historique indique les mathématiques, l’anglais, le français et l’histoire de secondaire 3. Pour le secondaire 4 et 5, elle indique des cours-ponts ou de mise à niveau en mathématiques et sciences, ainsi que des examens de reprise menant à la diplomation. Confirmez la liste actuelle des cours au moment de l’inscription." }] }],
    registrationUrl: "https://student.qbbe.ca/", relatedPrograms: ["academic-support", "bana"], meta: source(["https://qbbe.ca/programs/the-dacosta-hall-program/", "https://student.qbbe.ca/"], "needs-program-review", "Student portal confirmed summer 2026 registration; legacy subjects and grade bands need cycle-specific verification."),
  },
  {
    slug: "high-school-preparation",
    title: { en: "High School Preparation", fr: "Préparation à l’école secondaire" },
    summary: { en: "A transition-focused QBBE program preserved from the legacy site pending confirmation of its current delivery.", fr: "Un programme QBBE axé sur la transition, préservé du site historique en attente de confirmation de sa prestation actuelle." },
    audience: ["student", "parent"], needs: ["academic", "mentorship"],
    status: { en: "Requires QBBE confirmation", fr: "Confirmation de QBBE requise" },
    fullDescription: [{ en: "QBBE’s High School Preparation Program describes support for students transitioning into and through high school. Its legacy page says the Da Costa Hall transition program combined interactive workshops or tutorials with support for adapting to high school.", fr: "Le programme de préparation à l’école secondaire de QBBE décrit un soutien pour les élèves qui entrent au secondaire et y progressent. Sa page historique indique que le programme de transition Da Costa Hall combinait des ateliers ou tutoriels interactifs et du soutien pour s’adapter au secondaire." }],
    sections: [{ heading: { en: "Legacy workshop themes", fr: "Thèmes d’ateliers historiques" }, paragraphs: [{ en: "The source lists High School 101, time management, goal setting, organization, study skills, leadership, peer pressure, bullying and violence in relationships, conflict resolution, graffiti/vandalism, inclusion, and cultural diversity. It describes the intended outcome as greater confidence and less anxiety about entering high school.", fr: "La source indique : High School 101, gestion du temps, établissement d’objectifs, organisation, méthodes d’étude, leadership, pression des pairs, intimidation et violence dans les relations, résolution de conflits, graffitis et vandalisme, inclusion et diversité culturelle. Elle décrit comme résultat visé une confiance accrue et moins d’anxiété à l’entrée au secondaire." }] }],
    meta: source(["https://qbbe.ca/programs/high-school-preparation-program/", "https://qbbe.ca/board-of-directors/"], "needs-program-review", "Accessible through QBBE’s public WordPress API. Topics and outcome are retained as legacy content; current delivery, dates, and enrollment require confirmation."),
  },
];
