"use client";
import { useState } from "react";

export function DonationForm({ locale }: { locale: "en" | "fr" }) {
  const [amount, setAmount] = useState("50"); const [frequency, setFrequency] = useState<"once" | "monthly">("once"); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const presets = [25, 50, 100, 250];
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/checkout/donation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ amount: Number(amount), frequency, donor: Object.fromEntries(form), locale }) }); const payload = await response.json(); if (payload.url) window.location.assign(payload.url); else setNotice(payload.message ?? (locale === "en" ? "Thank you. Payment setup will be available shortly." : "Merci. La configuration du paiement sera bientôt disponible.")); setBusy(false); }
  return <form className="form-shell" onSubmit={submit}><p className="eyebrow" style={{ color: "var(--blue)" }}>{locale === "en" ? "Make a donation" : "Faire un don"}</p><h2 className="display" style={{ fontSize: "3rem", margin: ".4rem 0 1rem" }}>{locale === "en" ? "Your support creates opportunity." : "Votre soutien crée des occasions."}</h2><fieldset className="filter-group"><legend>{locale === "en" ? "Choose an amount" : "Choisir un montant"}</legend><div className="filter-list">{presets.map((value) => <button type="button" key={value} aria-pressed={amount === String(value)} onClick={() => setAmount(String(value))}>${value}</button>)}<label><span className="sr-only">Custom amount</span><input aria-label="Custom donation amount" min="1" type="number" value={amount} onChange={(e) => setAmount(e.target.value)} style={{ width: 120, padding: ".5rem" }} /></label></div></fieldset><fieldset className="filter-group"><legend>{locale === "en" ? "Frequency" : "Fréquence"}</legend><div className="filter-list"><button type="button" aria-pressed={frequency === "once"} onClick={() => setFrequency("once")}>{locale === "en" ? "Give once" : "Don unique"}</button><button type="button" aria-pressed={frequency === "monthly"} onClick={() => setFrequency("monthly")}>{locale === "en" ? "Give monthly" : "Don mensuel"}</button></div></fieldset><div className="form-row"><div className="field"><label htmlFor="donor-name">{locale === "en" ? "Name" : "Nom"}</label><input id="donor-name" required name="name" /></div><div className="field"><label htmlFor="donor-email">Email</label><input id="donor-email" required type="email" name="email" /></div></div><div className="field"><label htmlFor="designation">{locale === "en" ? "Direct my gift" : "Diriger mon don"}</label><select id="designation" name="designation"><option value="general">{locale === "en" ? "Where needed most" : "Là où le besoin est le plus grand"}</option><option value="academic">{locale === "en" ? "Academic programs" : "Programmes scolaires"}</option><option value="family">{locale === "en" ? "Family programs" : "Programmes familiaux"}</option><option value="technology">{locale === "en" ? "Technology education" : "Éducation technologique"}</option></select></div><div className="notice">{locale === "en" ? "Tax receipt eligibility and restricted fund designations are confirmed by QBBE before payment is finalized." : "L’admissibilité aux reçus fiscaux et les désignations de fonds sont confirmées par QBBE avant la finalisation du paiement."}</div><button className="button" disabled={busy}>{busy ? "…" : locale === "en" ? `Continue with $${amount}` : `Continuer avec ${amount} $`}</button>{notice && <p role="status">{notice}</p>}</form>;
}
