"use client";
import { useState } from "react";
import { donationContent } from "@/lib/content";

export function DonationForm({ locale }: { locale: "en" | "fr" }) {
  const [amount, setAmount] = useState("50"); const [frequency, setFrequency] = useState<"once" | "monthly">("once"); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const presets = [25, 50, 100, 250];
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/checkout/donation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ amount: Number(amount), frequency, donor: { ...Object.fromEntries(form), designation: "general" }, locale }) }); const payload = await response.json(); if (payload.url) window.location.assign(payload.url); else setNotice(payload.message ?? (locale === "en" ? "Online donations are not available yet. Please contact QBBE for approved giving options." : "Les dons en ligne ne sont pas encore offerts. Communiquez avec QBBE pour connaître les options approuvées.")); setBusy(false); }
  return <form className="form-shell" onSubmit={submit}><p className="eyebrow" style={{ color: "var(--blue)" }}>{locale === "en" ? "Make a donation" : "Faire un don"}</p><h2 className="display" style={{ fontSize: "3rem", margin: ".4rem 0 1rem" }}>{locale === "en" ? "Your support creates opportunity." : "Votre soutien crée des occasions."}</h2><fieldset className="filter-group"><legend>{locale === "en" ? "Choose an amount" : "Choisir un montant"}</legend><div className="filter-list">{presets.map((value) => <button type="button" key={value} aria-pressed={amount === String(value)} onClick={() => setAmount(String(value))}>${value}</button>)}<label><span className="sr-only">Custom amount</span><input aria-label="Custom donation amount" min="1" type="number" value={amount} onChange={(e) => setAmount(e.target.value)} style={{ width: 120, padding: ".5rem" }} /></label></div></fieldset><fieldset className="filter-group"><legend>{locale === "en" ? "Frequency" : "Fréquence"}</legend><div className="filter-list"><button type="button" aria-pressed={frequency === "once"} onClick={() => setFrequency("once")}>{locale === "en" ? "Give once" : "Don unique"}</button><button type="button" aria-pressed={frequency === "monthly"} onClick={() => setFrequency("monthly")}>{locale === "en" ? "Give monthly" : "Don mensuel"}</button></div></fieldset><div className="form-row"><div className="field"><label htmlFor="donor-name">{locale === "en" ? "Name" : "Nom"}</label><input id="donor-name" required name="name" /></div><div className="field"><label htmlFor="donor-email">Email</label><input id="donor-email" required type="email" name="email" /></div></div><div className="notice">{locale === "en" ? "Donations are currently directed to QBBE’s general work. Restricted designations, charity status, and tax-receipt eligibility require QBBE finance and legal approval before they are offered or promised." : "Les dons sont actuellement dirigés vers le travail général de QBBE. Les désignations restreintes, le statut d’organisme de bienfaisance et l’admissibilité aux reçus fiscaux nécessitent l’approbation des finances et du service juridique de QBBE avant d’être offerts ou promis."}</div><section className="notice" aria-labelledby="in-kind-heading"><h3 id="in-kind-heading">{donationContent.inKind.heading[locale]}</h3><p>{donationContent.inKind.body[locale]}</p></section><button className="button" disabled={busy}>{busy ? "…" : locale === "en" ? `Continue with $${amount}` : `Continuer avec ${amount} $`}</button>{notice && <p role="status">{notice}</p>}</form>;
}
