import type { Locale } from "@/lib/i18n";

export type Program = {
  slug: string; title: Record<Locale, string>; summary: Record<Locale, string>;
  audience: string[]; needs: string[]; age: string; format: Record<Locale, string>;
  status: Record<Locale, string>; schedule: Record<Locale, string>;
};

export const programs: Program[] = [
  { slug: "academic-support", title: { en: "Academic Support", fr: "Soutien scolaire" }, summary: { en: "Tutoring and study support that helps students build confidence and achieve their goals.", fr: "Du tutorat et un accompagnement qui aident les élèves à gagner en confiance et à atteindre leurs objectifs." }, audience: ["student", "parent"], needs: ["academic"], age: "Grades 3–11", format: { en: "In person & online", fr: "En personne et en ligne" }, status: { en: "Registration opens soon", fr: "Inscriptions bientôt ouvertes" }, schedule: { en: "After school", fr: "Après l’école" } },
  { slug: "early-literacy", title: { en: "Early Literacy", fr: "Éveil à la lecture" }, summary: { en: "Early interventions that give young learners a strong foundation for reading and learning.", fr: "Des interventions précoces qui donnent aux jeunes élèves de solides fondations en lecture et en apprentissage." }, audience: ["student", "parent"], needs: ["literacy"], age: "Ages 5–9", format: { en: "In person", fr: "En personne" }, status: { en: "Registration opens soon", fr: "Inscriptions bientôt ouvertes" }, schedule: { en: "Weekend sessions", fr: "Séances de fin de semaine" } },
  { slug: "future-careers", title: { en: "Future Careers", fr: "Carrières d’avenir" }, summary: { en: "Career exploration, mentorship and pathways to post-secondary success.", fr: "Exploration de carrières, mentorat et parcours vers la réussite postsecondaire." }, audience: ["student", "educator"], needs: ["career", "mentorship"], age: "Ages 14–18", format: { en: "Hybrid", fr: "Hybride" }, status: { en: "Join the waitlist", fr: "Joindre la liste d’attente" }, schedule: { en: "Monthly", fr: "Mensuel" } },
  { slug: "family-first", title: { en: "Family First", fr: "La famille d’abord" }, summary: { en: "Practical support that strengthens families’ role in every child’s education.", fr: "Un soutien concret qui renforce le rôle des familles dans l’éducation de chaque enfant." }, audience: ["parent", "community"], needs: ["family"], age: "Parents & guardians", format: { en: "In person & virtual", fr: "En personne et virtuel" }, status: { en: "Open", fr: "Ouvert" }, schedule: { en: "Seasonal workshops", fr: "Ateliers saisonniers" } },
  { slug: "learn-to-code", title: { en: "Learn to Code", fr: "Apprendre à coder" }, summary: { en: "Technology learning that equips young people to create, problem-solve and lead.", fr: "Un apprentissage technologique qui permet aux jeunes de créer, résoudre des problèmes et diriger." }, audience: ["student", "educator"], needs: ["technology"], age: "Ages 10–17", format: { en: "In person", fr: "En personne" }, status: { en: "Registration opens soon", fr: "Inscriptions bientôt ouvertes" }, schedule: { en: "School breaks", fr: "Congés scolaires" } },
  { slug: "bana", title: { en: "BANA", fr: "BANA" }, summary: { en: "Community-centred enrichment and mentorship for Black youth.", fr: "Un programme communautaire d’enrichissement et de mentorat pour les jeunes Noirs." }, audience: ["student", "community"], needs: ["mentorship"], age: "Youth", format: { en: "In person", fr: "En personne" }, status: { en: "Learn more", fr: "En savoir plus" }, schedule: { en: "Year-round", fr: "Toute l’année" } },
];

export const events = [
  { slug: "family-learning-night", date: "2026-09-18", type: { en: "Families", fr: "Familles" }, title: { en: "Family Learning Night", fr: "Soirée d’apprentissage en famille" }, location: { en: "Montreal · QBBE Learning Hub", fr: "Montréal · Centre d’apprentissage QBBE" }, description: { en: "An evening of practical tools, connection and learning for families.", fr: "Une soirée d’outils pratiques, de liens et d’apprentissage pour les familles." } },
  { slug: "educator-roundtable", date: "2026-10-08", type: { en: "Educators", fr: "Éducateurs" }, title: { en: "Educator Roundtable", fr: "Table ronde des éducateurs" }, location: { en: "Virtual", fr: "En ligne" }, description: { en: "A shared space for ideas, research and action in education.", fr: "Un espace commun pour les idées, la recherche et l’action en éducation." } },
  { slug: "ally-lunch-learn", date: "2026-10-23", type: { en: "Community", fr: "Communauté" }, title: { en: "QBBE Ally Lunch & Learn", fr: "Dîner-conférence des alliés QBBE" }, location: { en: "Montreal", fr: "Montréal" }, description: { en: "Meet the community advancing educational equity across Quebec.", fr: "Rencontrez la communauté qui fait progresser l’équité en éducation au Québec." } },
];

export const pageContent: Record<string, Record<Locale, { eyebrow: string; title: string; lead: string; sections: Array<[string, string]> }>> = {
  about: {
    en: { eyebrow: "About QBBE", title: "An educational institution rooted in community.", lead: "For more than 50 years, QBBE has created opportunities for Black and diverse communities across Quebec.", sections: [["Our story", "QBBE brings together students, families, educators, volunteers and partners around a shared belief: education can transform lives and communities."], ["A legacy of action", "Our history is lived through the people we support, the programs we deliver and the systems we help change."], ["Leadership and partners", "Our work is strengthened by a committed board, staff, volunteers and a network of community partners."]] },
    fr: { eyebrow: "À propos de QBBE", title: "Une institution éducative ancrée dans la communauté.", lead: "Depuis plus de 50 ans, QBBE crée des occasions pour les communautés noires et diverses du Québec.", sections: [["Notre histoire", "QBBE réunit élèves, familles, éducateurs, bénévoles et partenaires autour d’une conviction commune : l’éducation transforme des vies et des communautés."], ["Un héritage d’action", "Notre histoire se vit à travers les personnes que nous soutenons, les programmes que nous offrons et les systèmes que nous contribuons à changer."], ["Leadership et partenaires", "Notre travail est renforcé par un conseil engagé, du personnel, des bénévoles et un réseau de partenaires communautaires."]] },
  },
  impact: {
    en: { eyebrow: "Impact", title: "More than numbers.", lead: "Every statistic represents a student, family or opportunity. QBBE reports impact with care, clarity and context.", sections: [["Stories behind the numbers", "Our impact is visible in the confidence students gain, the families that find support and the educators who build better learning environments."], ["Reports and transparency", "Annual reports, financial statements and research are published here as they are reviewed and approved."], ["Measure what matters", "Program outcomes and organization-wide metrics will be maintained through QBBE’s verified reporting process."]] },
    fr: { eyebrow: "Impact", title: "Plus que des chiffres.", lead: "Chaque statistique représente un élève, une famille ou une occasion. QBBE communique son impact avec soin, clarté et contexte.", sections: [["Les histoires derrière les chiffres", "Notre impact se voit dans la confiance que gagnent les élèves, les familles qui trouvent du soutien et les éducateurs qui créent de meilleurs environnements d’apprentissage."], ["Rapports et transparence", "Les rapports annuels, états financiers et recherches sont publiés ici après leur révision et approbation."], ["Mesurer ce qui compte", "Les résultats des programmes et les mesures organisationnelles seront maintenus grâce au processus de rapports vérifiés de QBBE."]] },
  },
  resources: {
    en: { eyebrow: "Resources", title: "Knowledge for action.", lead: "Research, publications and practical guidance for students, families, educators and communities.", sections: [["Research", "Find evidence-informed resources that advance equitable educational practice."], ["For families", "Practical tools to help families navigate their children’s learning journey."], ["For educators", "Research, opportunities and resources to support inclusive learning environments."]] },
    fr: { eyebrow: "Ressources", title: "Des connaissances pour agir.", lead: "Recherche, publications et conseils pratiques pour les élèves, les familles, les éducateurs et les communautés.", sections: [["Recherche", "Découvrez des ressources fondées sur des données qui font progresser des pratiques éducatives équitables."], ["Pour les familles", "Des outils pratiques pour aider les familles à accompagner le parcours scolaire de leurs enfants."], ["Pour les éducateurs", "Recherche, occasions et ressources pour soutenir des milieux d’apprentissage inclusifs."]] },
  },
  "get-involved": {
    en: { eyebrow: "Get involved", title: "There is more than one way to make an impact.", lead: "Bring your time, expertise, resources or organization to the movement for educational equity.", sections: [["Become a QBBE Ally", "Corporate, business, educator and individual Allies make sustained community investment possible."], ["Volunteer", "Share skills, encouragement and time with students, families and programs."], ["Partner with QBBE", "Create meaningful opportunities through corporate, education and community partnerships."]] },
    fr: { eyebrow: "S’impliquer", title: "Il y a plus d’une façon d’avoir un impact.", lead: "Offrez votre temps, votre expertise, vos ressources ou votre organisation au mouvement pour l’équité en éducation.", sections: [["Devenir allié QBBE", "Les alliés corporatifs, commerciaux, éducatifs et individuels rendent possibles des investissements communautaires durables."], ["Bénévolat", "Partagez vos compétences, vos encouragements et votre temps avec les élèves, les familles et les programmes."], ["Devenir partenaire", "Créez des occasions significatives grâce aux partenariats corporatifs, éducatifs et communautaires."]] },
  },
};

export const allyPlans = {
  corporate: [{ tier: "Bronze", price: 1000 }, { tier: "Silver", price: 2500 }, { tier: "Gold", price: 5000 }],
  business: [{ tier: "Bronze", price: 250 }, { tier: "Silver", price: 500 }, { tier: "Gold", price: 750 }],
  educator: [{ tier: "Bronze", price: 50 }, { tier: "Silver", price: 100 }, { tier: "Gold", price: 150 }],
  individual: [{ tier: "Basic", price: 25 }, { tier: "Bronze", price: 50 }, { tier: "Silver", price: 100 }, { tier: "Gold", price: 150 }],
};
