export const redirects = [
  { source: "/about-us", destination: "/en/about", permanent: true },
  { source: "/history", destination: "/en/about/history", permanent: true },
  { source: "/board-of-directors", destination: "/en/about/leadership", permanent: true },
  { source: "/partners", destination: "/en/about/partners", permanent: true },
  { source: "/faqs", destination: "/en/resources/faq", permanent: true },
  { source: "/programs/academic-support", destination: "/en/programs/academic-support", permanent: true },
  { source: "/programs/early-literacy-program", destination: "/en/programs/early-literacy", permanent: true },
  { source: "/programs/future-careers", destination: "/en/programs/future-careers", permanent: true },
  { source: "/family-first-program", destination: "/en/programs/family-first", permanent: true },
  { source: "/learn-to-code", destination: "/en/programs/learn-to-code", permanent: true },
  { source: "/programs/the-bana-program-2", destination: "/en/programs/bana", permanent: true },
  { source: "/programs/the-dacosta-hall-program", destination: "/en/programs/da-costa-hall", permanent: true },
  { source: "/programs/high-school-preparation-program", destination: "/en/programs/high-school-preparation", permanent: true },
  { source: "/volunteers", destination: "/en/get-involved/volunteer", permanent: true },
  { source: "/donate", destination: "/en/donate", permanent: true },
  { source: "/contact-2", destination: "/en/about/contact", permanent: true },
  { source: "/upcoming-events-3", destination: "/en/events", permanent: true },
  { source: "/membership-plans", destination: "/en/get-involved/membership", permanent: true },
  { source: "/family-first-program-registration", destination: "/en/programs/family-first", permanent: true },
  { source: "/programs/future-careers/jobs-of-the-future-myel-program-registration", destination: "/en/programs/future-careers", permanent: true },
  { source: "/our-history", destination: "/en/about/history", permanent: true },
  { source: "/reports/2020-annual-report", destination: "/en/impact/reports", permanent: true },
  { source: "/reports/2000-financial-statement", destination: "/en/impact/financial-transparency", permanent: true },
  { source: "/fr/lhistoire", destination: "/fr/about/history", permanent: true },
  { source: "/fr/faq", destination: "/fr/resources/faq", permanent: true },
] as const;
