import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { ContactForm } from "@/components/contact-form";
import { pageContent } from "@/lib/content";
import { isLocale, localePath } from "@/lib/i18n";

const knownPaths = new Set(["about", "about/our-story", "about/history", "about/mission", "about/leadership", "about/partners", "about/contact", "impact", "impact/stories", "impact/reports", "impact/research", "impact/financial-transparency", "resources", "resources/research", "resources/publications", "resources/parents", "resources/students", "resources/educators", "resources/faq", "get-involved", "get-involved/volunteer", "get-involved/educators", "get-involved/corporate-partners", "get-involved/community-partners"]);
function rootKey(path: string) { return path.startsWith("about") ? "about" : path.startsWith("impact") ? "impact" : path.startsWith("resources") ? "resources" : "get-involved"; }
export default async function ContentPage({ params }: { params: Promise<{ locale: string; slug: string[] }> }) { const { locale, slug } = await params; if (!isLocale(locale)) notFound(); const path = slug.join("/"); if (!knownPaths.has(path)) notFound(); const content = pageContent[rootKey(path)][locale]; const specific = path !== rootKey(path) ? slug.at(-1)?.replaceAll("-", " ") : undefined; const formType = path === "get-involved/volunteer" ? "volunteer" : path.includes("partners") ? "partner" : path === "about/contact" ? "contact" : null; return <><PageHero eyebrow={specific ? specific : content.eyebrow} title={specific ? specific.replace(/\b\w/g, (char) => char.toUpperCase()) : content.title} lead={content.lead} /><section className="section"><div className="shell content-grid"><article className="prose">{content.sections.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}<Link className="button" href={localePath(locale, path.startsWith("get-involved") ? "/get-involved/membership" : "/programs")}>{locale === "en" ? "Take the next step" : "Passez à la prochaine étape"}<ArrowRight size={16} /></Link></article><aside className="detail-meta"><dl><dt>{locale === "en" ? "Content status" : "État du contenu"}</dt><dd>{locale === "en" ? "Under QBBE editorial review" : "En révision éditoriale par QBBE"}</dd><dt>{locale === "en" ? "Language" : "Langue"}</dt><dd>{locale === "en" ? "English" : "Français"}</dd></dl></aside></div>{formType && <div className="shell" style={{ marginTop: "3rem" }}><ContactForm locale={locale} type={formType} /></div>}</section></>; }
