import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { ProgramFinder } from "@/components/program-finder";
import { NewsletterForm } from "@/components/newsletter-form";
import { copy, isLocale, localePath } from "@/lib/i18n";
import { events } from "@/lib/content";
import { formatDate } from "@/lib/utils";
import { notFound } from "next/navigation";

export default async function Home({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: candidate } = await params; if (!isLocale(candidate)) notFound(); const locale = candidate; const t = copy[locale];
  return <>
    <section className="hero"><div className="shell hero-copy"><p className="eyebrow">{locale === "en" ? "Quebec Board of Black Educators" : "Quebec Board of Black Educators"}</p><h1 className="display">{locale === "en" ? <>Empowering Students.<br />Strengthening Families.<br />Transforming Education.</> : <>Élever les élèves.<br />Renforcer les familles.<br />Transformer l’éducation.</>}</h1><p className="lede">{locale === "en" ? "For more than 50 years, QBBE has advanced educational opportunity, equity and achievement for Black and diverse communities across Quebec." : "Depuis plus de 50 ans, QBBE fait progresser les occasions, l’équité et la réussite scolaires pour les communautés noires et diverses du Québec."}</p><div className="hero-actions"><Link className="button button--gold" href={localePath(locale, "/programs")}>{t.explore}<ArrowRight size={17} /></Link><Link className="button button--light" href={localePath(locale, "/about")}>{t.discover}</Link></div></div></section>
    <section className="section" style={{ padding: "2.4rem 0" }}><div className="shell"><p className="eyebrow" style={{ color: "var(--blue)" }}>{locale === "en" ? "Serving Quebec communities for more than 50 years" : "Au service des communautés du Québec depuis plus de 50 ans"}</p><div className="metrics"><div className="metric"><strong>50+</strong><span>{locale === "en" ? "years of community action" : "ans d’action communautaire"}</span></div><div className="metric"><strong>8</strong><span>{locale === "en" ? "core programs" : "programmes principaux"}</span></div><div className="metric"><strong>∞</strong><span>{locale === "en" ? "potential unlocked" : "potentiel libéré"}</span></div><div className="metric"><strong>1</strong><span>{locale === "en" ? "shared purpose" : "objectif commun"}</span></div></div></div></section>
    <ProgramFinder locale={locale} />
    <section className="story"><div className="story-image" role="img" aria-label="Students sharing a moment together" /><div className="story-copy section--blue"><p className="eyebrow">{locale === "en" ? "Impact story" : "Histoire d’impact"}</p><blockquote>{locale === "en" ? "Education changes more than grades." : "L’éducation change plus que les notes."}</blockquote><p style={{ lineHeight: 1.65 }}>{locale === "en" ? "It creates confidence, connection and new possibilities for students, families and communities." : "Elle crée de la confiance, des liens et de nouvelles possibilités pour les élèves, les familles et les communautés."}</p><Link className="button button--light" href={localePath(locale, "/impact/stories")}>{locale === "en" ? "Read their story" : "Lire leur histoire"}<ArrowRight size={16} /></Link></div></section>
    <section className="section section--blue"><div className="shell"><p className="eyebrow">{locale === "en" ? "Our legacy" : "Notre héritage"}</p><h2 className="display section-heading">{locale === "en" ? "Since 1968." : "Depuis 1968."}</h2><div className="timeline"><div className="timeline-inner">{[["1968", "A commitment to improving educational opportunity takes root."], ["1980s", "Community programs expand to meet students where they are."], ["2000s", "QBBE strengthens family support and partnership work."], ["Today", "Programs, advocacy and research create connected impact."], ["Next", "A new generation shapes a more equitable educational future."]].map(([year, text]) => <article className="milestone" key={year}><time>{year}</time><p>{text}</p></article>)}</div></div><Link className="button button--light" href={localePath(locale, "/about/history")}>{locale === "en" ? "Explore our history" : "Explorer notre histoire"}</Link></div></section>
    <section className="section"><div className="shell"><p className="eyebrow">QBBE Ally</p><h2 className="display section-heading">{locale === "en" ? "Become a QBBE Ally." : "Devenez allié QBBE."}</h2><p className="lede">{locale === "en" ? "There is more than one way to make an impact." : "Il y a plus d’une façon d’avoir un impact."}</p><div className="ally-grid">{[["Corporate", "Lead meaningful change with your organization."], ["Business", "Invest locally in student and family success."], ["Educator", "Join an education network built for action."], ["Individual", "Move educational equity forward, together."]].map(([title, text]) => <Link key={title} className="ally-item" href={localePath(locale, "/get-involved/membership")}><p className="eyebrow" style={{ color: "var(--blue)" }}>{locale === "en" ? "QBBE Ally" : "Allié QBBE"}</p><h3>{title}</h3><p>{text}</p><ArrowUpRight size={19} /></Link>)}</div></div></section>
    <section className="section section--stone"><div className="shell split"><div><p className="eyebrow" style={{ color: "var(--blue)" }}>{locale === "en" ? "Upcoming" : "À venir"}</p><h2 className="display section-heading">{locale === "en" ? "Meet us in the community." : "Rencontrez-nous dans la communauté."}</h2><Link className="button" href={localePath(locale, "/events")}>{locale === "en" ? "See all events" : "Voir tous les événements"}</Link></div><div className="event-list">{events.map((event) => <Link className="list-item" href={localePath(locale, `/events/${event.slug}`)} key={event.slug}><time>{formatDate(event.date, locale)}</time><div><h3>{event.title[locale]}</h3><p>{event.location[locale]}</p></div><ArrowUpRight /></Link>)}</div></div></section>
    <section className="section" style={{ background: "var(--blue-deep)", color: "white" }}><div className="shell split"><div><p className="eyebrow">{locale === "en" ? "Stay connected" : "Restez informé"}</p><h2 className="display section-heading">{locale === "en" ? "The work continues." : "Le travail continue."}</h2><p className="lede" style={{ color: "rgba(255,255,255,.72)" }}>{locale === "en" ? "Get QBBE news, programs and opportunities in your inbox." : "Recevez les nouvelles, programmes et occasions de QBBE dans votre boîte courriel."}</p></div><div style={{ alignSelf: "end" }}><NewsletterForm locale={locale} /></div></div></section>
  </>;
}
