import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { NewsletterForm } from "@/components/newsletter-form";
import { ProgramFinder } from "@/components/program-finder";
import { copy, isLocale, localePath } from "@/lib/i18n";
import { notFound } from "next/navigation";

export default async function Home({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: candidate } = await params;
  if (!isLocale(candidate)) notFound();
  const locale = candidate;
  const t = copy[locale];
  return <>
    <section className="hero"><div className="shell hero-copy"><p className="eyebrow">Quebec Board of Black Educators</p><h1 className="display">{locale === "en" ? <>Envisioning a better future<br />through education.</> : <>Envisager un avenir meilleur<br />grâce à l’éducation.</>}</h1><p className="lede">{locale === "en" ? "QBBE is a nonprofit education and research institution supporting educational opportunity, awareness of educational bias, and communities of colour across Quebec." : "QBBE est une institution d’éducation et de recherche à but non lucratif qui soutient les possibilités éducatives, la sensibilisation aux préjugés en éducation et les communautés de couleur au Québec."}</p><div className="hero-actions"><Link className="button button--gold" href={localePath(locale, "/programs")}>{t.explore}<ArrowRight size={17} /></Link><Link className="button button--light" href={localePath(locale, "/about/mission")}>{locale === "en" ? "Our mission" : "Notre mission"}</Link></div></div></section>
    <section className="section" style={{ padding: "2.4rem 0" }}><div className="shell"><p className="eyebrow" style={{ color: "var(--blue)" }}>{locale === "en" ? "A documented legacy" : "Un héritage documenté"}</p><div className="metrics"><div className="metric"><strong>1968</strong><span>{locale === "en" ? "QBBE’s stated founding era" : "époque de fondation déclarée de QBBE"}</span></div><div className="metric"><strong>1971</strong><span>{locale === "en" ? "legal registration recorded by QBBE" : "enregistrement légal indiqué par QBBE"}</span></div><div className="metric"><strong>QBBE</strong><span>{locale === "en" ? "education, research, advocacy, and community support" : "éducation, recherche, plaidoyer et soutien communautaire"}</span></div></div></div></section>
    <ProgramFinder locale={locale} />
    <section className="story"><div className="story-image" role="img" aria-label={locale === "en" ? "Students learning together" : "Élèves qui apprennent ensemble"} /><div className="story-copy section--blue"><p className="eyebrow">{locale === "en" ? "Why this work matters" : "Pourquoi ce travail compte"}</p><blockquote>{locale === "en" ? "Education is a shared community project." : "L’éducation est un projet communautaire partagé."}</blockquote><p style={{ lineHeight: 1.65 }}>{locale === "en" ? "QBBE’s programs, research, advocacy, and family support are connected ways of advancing educational opportunity. Individual testimonials will be added only with approval and consent." : "Les programmes, la recherche, le plaidoyer et le soutien aux familles de QBBE sont des façons interreliées de faire avancer les possibilités éducatives. Les témoignages individuels ne seront ajoutés qu’avec approbation et consentement."}</p><Link className="button button--light" href={localePath(locale, "/impact/stories")}>{locale === "en" ? "Explore QBBE’s impact" : "Explorer l’impact de QBBE"}<ArrowRight size={16} /></Link></div></section>
    <section className="section section--blue"><div className="shell"><p className="eyebrow">{locale === "en" ? "Our legacy" : "Notre héritage"}</p><h2 className="display section-heading">{locale === "en" ? "A history we can trace." : "Une histoire que nous pouvons retracer."}</h2><div className="timeline"><div className="timeline-inner" style={{ gridTemplateColumns: "repeat(3, minmax(220px, 1fr))", minWidth: 660 }}><article className="milestone"><time>Late 1960s</time><p>{locale === "en" ? "QBBE records an educational context in which Caribbean immigrant children faced cultural and educational barriers." : "QBBE documente un contexte éducatif dans lequel les enfants immigrants des Caraïbes faisaient face à des obstacles culturels et éducatifs."}</p></article><article className="milestone"><time>1968</time><p>{locale === "en" ? "Concerned Black educators, mostly from the Caribbean, formed QBBE in response to community needs." : "Des éducatrices et éducateurs noirs préoccupés, majoritairement originaires des Caraïbes, ont créé QBBE en réponse aux besoins de la communauté."}</p></article><article className="milestone"><time>1971</time><p>{locale === "en" ? "QBBE states it was legally registered on December 29, 1971." : "QBBE indique avoir été légalement enregistré le 29 décembre 1971."}</p></article></div></div><Link className="button button--light" href={localePath(locale, "/about/history")}>{locale === "en" ? "Explore our history" : "Explorer notre histoire"}</Link></div></section>
    <section className="section"><div className="shell"><p className="eyebrow">QBBE Ally</p><h2 className="display section-heading">{locale === "en" ? "Become a QBBE Ally." : "Devenez allié QBBE."}</h2><p className="lede">{locale === "en" ? "Ally membership is distinct from giving. Prices and benefits remain under QBBE review until payment plans are confirmed." : "L’adhésion Allié est distincte d’un don. Les prix et avantages restent en révision par QBBE jusqu’à confirmation des plans de paiement."}</p><div className="ally-grid">{[["Corporate", "Lead meaningful change with your organization."], ["Business", "Invest locally in student and family success."], ["Educator", "Join an education network built for action."], ["Individual", "Move educational equity forward, together."]].map(([title, text]) => <Link key={title} className="ally-item" href={localePath(locale, "/get-involved/membership")}><p className="eyebrow" style={{ color: "var(--blue)" }}>QBBE Ally</p><h3>{locale === "en" ? title : ({ Corporate: "Corporation", Business: "Entreprise", Educator: "Éducateur", Individual: "Individuel" }[title] ?? title)}</h3><p>{locale === "en" ? text : "Découvrez les possibilités d’adhésion et les détails à confirmer avec QBBE."}</p><ArrowUpRight size={19} /></Link>)}</div></div></section>
    <section className="section section--stone"><div className="shell split"><div><p className="eyebrow" style={{ color: "var(--blue)" }}>{locale === "en" ? "Events" : "Événements"}</p><h2 className="display section-heading">{locale === "en" ? "Watch for the next gathering." : "Surveillez le prochain rassemblement."}</h2><p className="lede">{locale === "en" ? "No upcoming event is published until QBBE confirms its details. Join the newsletter for approved program and event updates." : "Aucun événement à venir n’est publié avant que QBBE confirme ses détails. Inscrivez-vous à l’infolettre pour recevoir les mises à jour approuvées sur les programmes et événements."}</p><Link className="button" href={localePath(locale, "/events")}>{locale === "en" ? "Visit events" : "Voir les événements"}</Link></div></div></section>
    <section className="section" style={{ background: "var(--blue-deep)", color: "white" }}><div className="shell split"><div><p className="eyebrow">{locale === "en" ? "Stay connected" : "Restez informé"}</p><h2 className="display section-heading">{locale === "en" ? "The work continues." : "Le travail continue."}</h2><p className="lede" style={{ color: "rgba(255,255,255,.72)" }}>{locale === "en" ? "Get QBBE news, programs, and opportunities in your inbox." : "Recevez les nouvelles, les programmes et les occasions de QBBE dans votre boîte courriel."}</p></div><div style={{ alignSelf: "end" }}><NewsletterForm locale={locale} /></div></div></section>
  </>;
}
